### ISSUE TITLE
Extend RNNLayer

### ISSUE THREAD

**Issue by allnes** [ARM-software/ComputeLibrary#1014]
Hi!

My name is Nesterov Alexander and I developer of [OpenVINO](https://github.com/openvinotoolkit) Toolkit ([contribution part](https://github.com/openvinotoolkit/openvino_contrib)). We use ComputeLibrary(ACL) as a backend for our ARM plugin.

We try map yours layers to our operations. And now we try use ACL [RNNLayer](https://arm-software.github.io/ComputeLibrary/latest/classarm__compute_1_1_n_e_r_n_n_layer.xhtml) with OpenVINO [RNNCell](https://docs.openvino.ai/latest/openvino_docs_ops_sequence_RNNCell_3.html). We get limitation for RNNLayer depend on clip parameter ([reference](https://github.com/openvinotoolkit/openvino/blob/master/src/core/reference/include/ngraph/runtime/reference/rnn_cell.hpp) of OpenVINO operation).

Do you have a plan for extend this operation?

Cc @alvoron
Thank you!

**Comment by allnes** [comment]
For more understanding.
Clip parameter with float value (e.c. = C) in RNNCell operation is clipping data (from -C to C) before activation. Alas in RNNLayer I don't find clipping before activation, that is difference in operations create big error.

**Comment by morgolock** [comment]
Hi Alexander,

ACL does not support the clip parameter presently: https://github.com/ARM-software/ComputeLibrary/blob/main/arm_compute/runtime/NEON/functions/NERNNLayer.h

How does this clip argument work on your side. Are the values to be clipped just before the final activation? https://github.com/ARM-software/ComputeLibrary/blob/main/src/runtime/NEON/functions/NERNNLayer.cpp#L103 .

Can't you not use LU_BOUNDED_RELU for the final activation? It's doing just that: https://github.com/ARM-software/ComputeLibrary/blob/main/src/cpu/kernels/activation/generic/neon/impl.h#L118

Hope this helps.

**Comment by allnes** [comment]
> 

Yes, all values are clipped just before the final activation. And we use LU_BOUNDED_RELU for RELU, but alas it doesn't work for TANH and LOGISTIC activation.

**Comment by allnes** [comment]
As I know tflite use Compute Library with clip, could you provide how it works?

**Comment by morgolock** [comment]
Hi @allnes 

I'm not familiar with the way tflite implements clipping in RNNLayer.

Since you have the test cases in place, please consider contributing to ACL and uploading an small patch for review implementing the changes for this small feature request.

It looks like the clipping can be done by adding a new kernel to `NERNNLayer` and running the new kernel before the final activation: 
https://github.com/ARM-software/ComputeLibrary/blob/main/src/runtime/NEON/functions/NERNNLayer.cpp#L127
https://github.com/ARM-software/ComputeLibrary/blob/main/src/runtime/NEON/functions/NERNNLayer.cpp#L144

You'll need to make changes to the interface to specify the min/max values for clipping.

Hope this helps.

**Comment by allnes** [comment]
@morgolock thank you for answer
