### ISSUE TITLE
How to implement my own runtime if I just need a little core kernel ?

### ISSUE THREAD

**Issue by wenhyan** [ARM-software/ComputeLibrary#1054]
Hi，I want to implement my own runtime for maximum performance, Is there some support? thx.

**Comment by wenhyan** [comment]
Hi @morgolock  
Thank you for your help. I want to use ARM CL on hardware without system support (like Linux), also don't support C++ std library and dynamic memory allocation (new or malloc or make_unique ...).
Do you have some idea?
Thx.

**Comment by morgolock** [comment]
Hi @wenhyan 

We support bare metal builds see https://arm-software.github.io/ComputeLibrary/v23.05/how_to_build.xhtml#S1_5_bare_metal .

Compute Library requires support for `-std=c++14`.

Can you be more specific about the hardware? 

Hope this helps.

**Comment by wenhyan** [comment]
Hi @morgolock 
The hardware is a A57 bare metal, but don't support c++14.
I think graph and runtime module requires support for c++14. Does the core module also need c++14?

**Comment by morgolock** [comment]
Hi @wenhyan 

Yes, `libarm_compute.so` requires `-std=c++14`. Please ignore `libarm_compute_core.so` since it's been deprecated and will be removed in the near future. See more details in https://review.mlplatform.org/c/ml/ComputeLibrary/+/9760


You can get a toolchain that supports `-std=c++14` and the code generated will run on bare metal. You just need to disable `openmp=0 cppthreads=0` as explained in the documentation.
