### ISSUE TITLE
using CL-library : same execution time with debug + assert and no-debug + no-assert

### ISSUE THREAD

**Issue by joel-mi** [ARM-software/ComputeLibrary#117]
I'm using Arm Compute Library for running on MALI GPU; the command I'm entering on Cygwin64 Terminal for this purpose is :
scons.bat Werror=1 -j8 debug=0 asserts=0 neon=0 opencl=1 embed_kernels=1 os=android arch=arm64-v8a
I'm using Android Studio as IDE under Windows-7
At this point I'm calculating elapsed time rather than execution time.
The elapsed time I got for 1 convolution layer run is about 5.5 ms, and for a network consisting of 7 convolution layers, 7 RELUs and 3 Max Pool layers - about 130 ms; the configuration time for this network is about 770 ms
What I find disturbing is that there is no significant difference between those timings and the one I got when building Arm Compute Library with debug=1 and asserts=1

When running on NEON (building with neon=1 and opencl=0), I saw a dramatic difference in timing between elapsed time for debug=0/asserts=0 and elapsed time for debug=1/asserts=1, when configuring and running the same network as above :
- configuration of whole network : with debug/assert - 13.8 ms, without debug/assert : 8.7 ms
- running single convolution layer : with debug/assert - 28.8 ms, without debug/assert : 1.84 ms
- running full network : with debug/assert - 257.3 ms, without debug/assert : 16.59 ms
As we see, for NEON without debug/assert, Convolution time was therefore somewhat shorter (by 37%), but run time was shorter by 83% !
So why don't we see any noticeable difference for MALI GPU ?

**Comment by gmiodice** [comment]
Hi @joel-mi 

when you build with debug=1, the impact on the performance is mainly on the CPU sice because the cpp will be built with the -O0 flag instead of -03 (https://github.com/ARM-software/ComputeLibrary/blob/master/sconscript#L263). 

Since for the OpenCL kernel there isn't this kind of flag for controlling the compiler optimizations (or better, we do not use -cl-opt-disable for disabling the compiler optimization), I wouldn't expect significant degradation of the performance on the GPU side.

Hope this can help,
Thanks

**Comment by kongxz** [comment]
@joel-mi 
I am using NENO too. However, the performance on my side is not as good as yours. Running single convolution layer will take 16.4ms. Can you tell more details of your testing? What's the input size and kernel size you used?  I just want to make sure if the performance is reasonable. Below is the information when i did the testing.
build config: neon=1 opencl=0 debug=0 asserts=0 embed_kernels=1 os=android arch=arm64-v8a
input size: 1 x 3 x 224 x 224
kernel size: 48 x 3 x 3 x 3
stride: 1, 1
padding: 1, 1
device: google pixel.
running single convolution layer : 16.4 ms

Thanks

**Comment by joel-mi** [comment]
@kongxz 
My input is a much smaller picture of 32x32x3, and kernel size = 40x3x3x3
So this would probably account for the difference in timing, I think that your timing is actually better than mine because your input is 49 times larger
I'm running on Arm A53

**Comment by joel-mi** [comment]
@gmiodice 

I'm attaching some timing measurements related to some of the layers of our network, and we are disappointed by the poor performance when running on GPU (much slower than NEON, as you can see)
the GPU we are using is T880M12 @650 MHz
When using a proprietary software framework for running the same layers on this GPU, the total run time (for all layers !) is about 7 ms, instead of 165 ms with Arm Compute Library / CL
Do you have any clues about the cause of this low performance on GPU ? Could it be that openCL is running on NEON CPU instead of GPU ?
Do you have any ideas about how to improve performance on GPU ?
[run_time_neon_vs_gpu.docx](https://github.com/ARM-software/ComputeLibrary/files/1018933/run_time_neon_vs_gpu.docx)

**Comment by gmiodice** [comment]
Hi @joel-mi ,

thanks for sharing the timing measurements related to your network. The poor performance for the Activation and Pooling Layers will be fixed in the next release. The issue was behind the dispatch of the tensor's slice on the CPU side which caused a significant overhead. In the next release will be used the 3rd dimension of the OpenCL NDRange to access the element of the correct slice.

For what concerns the performance of the convolution layer, how did you measure the time? How many iterations did you use for evaluating the performance?

Thanks,

**Comment by kaishijeng** [comment]
I ran cl_convolution and neon_convolution from example application on firefly 3399 (2xA57, 4xA53./T860Mali). cl_convolution runs faster than neon_convolution on thi splatform:
cl_convolution: 0.000745sec
neon_convolution: 0.001184sec

If you want to share your network application, I can give it a try on firefly3399
The biggest issue with ComputeLibrary is that there is no well-known CNN network example (like alexnet) which we can do benchmark. Without this, it is very difficult  to assess library performance against other framework/library.

Thanks,

**Comment by joel-mi** [comment]
@gmiodice 
I tried to run the same sequence of layers 5 times in a row
on NEON, there was no noticeable difference between 1st run and subsequent runs
but on GPU, run time for convolution and fully connected layers got considerably shorter :
for a network of 7 convolution layers and 2 fully connected layers, 1st run took 89ms, while average for next 4 runs was 3.85 ms - these are good news indeed !

**Comment by AnthonyARM** [comment]
@joel-mi That's probably because of the cache maintenance: every time you access a buffer on the CPU side, some cache maintenance needs to happen before it can be used on the GPU side again.
Make sure your CPU is set to performance mode even for OpenCL runs.

If you want to make sure this is indeed the cache maintenance you can try to allocate and fill your buffers, then create an OpenCL kernel which takes all your buffers as arguments, call clFinish(), then run all your layers as you would normally do: I would expect the execution time of the first run to be now similar to the subsequent ones.

**Comment by gmiodice** [comment]
Hi @joel-mi,

I am very happy to know you have found the reason for poor performance. Yesterday I asked "how many iterations" because the first run should be the slowest one. The reason is that **just** for the first run we dispatch some kernels for reshaping the weights in the tensors.

Thanks,

**Comment by joel-mi** [comment]
@gmiodice 
Hi Gian Marco, you previously mentioned that "poor performance for the Activation and Pooling Layers will be fixed in the next release" - when is next release due ?

When this issue is fixed in next release, do you expect that RELU and max pooling will then run faster on GPU than on NEON ?

**Comment by gmiodice** [comment]
Hi @joel-mi ,

the next release will be in June ( so soon :) ). Regarding your question:
do you expect that RELU and max pooling will then run faster on GPU than on NEON?
The answer is: depends. 
Depends on: how many cores there are on the GPUs/CPUs, frequency 
Anyway with this fix, the performance of both layers should be improved significantly on the GPU side. 

Thanks

**Comment by GeorgeARM** [comment]
Closing this as seems that the issue has been addressed. Next release is at the end of this week. Reopen if required.
