### ISSUE TITLE
pure virtual method called

### ISSUE THREAD

**Issue by sundw2014** [ARM-software/ComputeLibrary#12]
I build the project with the follwing command on a __raspberry2 Model B__:
```
scons Werror=1 -j8 debug=1 asserts=1 arch=armv7a os=linux build=native opencl=0 neon=1
```
Then,
```
cd build
LD_LIBRARY_PATH=. ./neon_convolution
```
But got output like this:
```pure virtual method called
terminate called without an active exception
Aborted
```
I found that it crashed in ```conv3x3.run()```.

gcc/g++ version:
```
gcc version 4.8.4 (Raspbian 4.8.4-1)
```
What's wrong?
Thank you.

**Comment by sundw2014** [comment]
OK, in ```src/runtime/NEON/functions/NEConvolution.cpp```, there is no ```NEConvolution3x3::run()```.

**Comment by AnthonyARM** [comment]
Hi,
Unfortunately I don't have a Raspberry Pi to reproduce this issue.

A few things I would suggest you try:

1) Could you please try to run the binaries we provided here: https://github.com/ARM-software/ComputeLibrary/releases

2) Cross compile instead of building natively  (In case it is a problem with the Raspberry Pi toolchain)

3) Try to run the example in GDB to see where it crashes.

We've successfully run this example on a variety of platforms so I'm curious to have more information about the issue you're seeing.

**Comment by AnthonyARM** [comment]
I only just noticed you were running Raspbian: isn't this OS compiled for armv6 ? (i.e no NEON support)

Have you tried using an armv7 hard float image instead ?
Should be faster too.

**Comment by sundw2014** [comment]
Hi @AnthonyARM ,
I found that it crashed in ```std::thread```. And it can be solved by removing ```-march=armv7-a -mthumb``` in the compiler flags.
Details of my Raspbian:
```
uname -a
Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux
```
I really want to know what is ```armv7l``` and I didn't find it in the ```-march``` lists.

Maybe, it is a bug with the toolchain.

**Comment by AnthonyARM** [comment]
Yes, like mentioned above: raspbian is compiled for armv6 which is why it works when you remove armv7-a and thumb.

Could you try with a Linux armv7 OS ? ((Like [Arch Linux](https://archlinuxarm.org/platforms/armv7/broadcom/raspberry-pi-2) or [Ubuntu](http://www.techrepublic.com/article/how-to-get-ubuntu-desktop-on-the-raspberry-pi-2/)))

**Comment by sundw2014** [comment]
Hi @AnthonyARM ,
Thank you.
I will try Arch Linux and tell you the result later.

**Comment by sundw2014** [comment]
Yes, it worked on Arch Linux.
```
uname -a
Linux alarmpi 4.9.19-1-ARCH #1 SMP Thu Mar 30 19:23:11 MDT 2017 armv7l GNU/Linux
```

**Comment by AnthonyARM** [comment]
Cool, thanks for confirming.
Feel free to re-open the issue or create a new one if you run into more problems
