### ISSUE TITLE
NEConvolutionKernel Only supports integer convolution

### ISSUE THREAD

**Issue by tanyuan1992** [ARM-software/ComputeLibrary#134]
Hi:
When I used NEConvolution on my platform,I see NEConvolutionKernel only support U8 and S16 but not support F16 or F32 recently.I would like to ask how I should  implement float point version of the NEConvolution.And I wanna know Why this library does not implement this function. Is there some technical problems?

**Comment by AnthonyARM** [comment]
I assume you want F32 support in order to do some machine learning convolution, right ?
[NEConvolution3x3](https://arm-software.github.io/ComputeLibrary/v17.05/classarm__compute_1_1_n_e_convolution3x3.xhtml) is the computer vision convolution for images
[NEConvolutionLayer](https://arm-software.github.io/ComputeLibrary/v17.05/classarm__compute_1_1_n_e_convolution_layer.xhtml) is the machine learning one (Which does support F32)
