### ISSUE TITLE
How to handle this situation in the softmax layer if the number overflows?

### ISSUE THREAD

**Issue by ppplinday** [ARM-software/ComputeLibrary#148]
For example, if the input have 5 number:8, 18, 28, 38, 48
the output will like this:
![softmax1](https://user-images.githubusercontent.com/23491538/27533122-0a180cbc-5a95-11e7-817c-7576b9f18180.png)
because according to the softmax calculation：we need to add exp(8)...exp(48) together. However, exp(48) is too big for c++ and it overflows. So how to handle this situation?
And if the input are:1, 2, 3, 4, 5
everything is fine because they are not too big.
Any helps or hints are appreciate!!!

**Comment by GeorgeARM** [comment]
Hello @ppplinday,

As you mentioned exp is a bit easy to overflow. To avoid special cases and paths in NEON calculations we do not report/check nans and infinities instead we continue to perform the calculations as normal that why you get these strange numbers instead of -inf.
I don't think there is much to do than normalizing your values to a smaller range.
We could have a look and try to saturate the values internally and check if the results are what we expect, but I am not quite sure that this is correct.

Regards,
George

**Comment by GeorgeARM** [comment]
@ppplinday  we will address this issue and fix it in the next maintenance release. For now you can normalize your values to avoid it.

**Comment by ppplinday** [comment]
@GeorgeARM  Thank you so much! Waiting for next release!
