### ISSUE TITLE
Complete example for machine learning

### ISSUE THREAD

**Issue by shakith** [ARM-software/ComputeLibrary#168]
Is there a complete machine learning example that is running with the ARM compute library?
neon_cnn.cpp example doesn't contain weights (or how to initialize the weights) or the input image. The benchmark alexnet/lenet5 seems to be using random data. Is there a plan release a complete example?

**Comment by AnthonyARM** [comment]
The example is here to show you how to create the layers and connect them together, using random values instead of the real values doesn't change anything to the performance of the library.

The weights files are too large to distribute in this repository and don't really bring any value to the example which is why we've got no plans to release them (You can easily find them in various places on internet already)

Also you could easily replace the random values with values from files if you wanted to: you just need to replace the `fill_random` method by a function which loads the values from a file.

**Comment by shakith** [comment]
Thanks. This can be closed now.
