### ISSUE TITLE
benchmark_tests timing in case of CL kernels (GPU)

### ISSUE THREAD

**Issue by atrah22** [ARM-software/ComputeLibrary#171]
Hello,

I wanted to know, what timing is more accurate in case of Mali-G71 GPU benchmarking.

I am running,
adb shell "/data/local/tmp/arm_compute_benchmark --benchmark_format=json /data/local/tmp/data/ --benchmark_filter=GEMMFP16GoogLeNet1"

And the output is,
```json
{
      "name": "GEMMFP16GoogLeNet1/cl_googlenet/GEMM_A(1152, 196)_B(256, 1152)_C(256, 196)_D(256, 196)_alpha1_beta0:29/threads:1",
      "iterations": 2291,
      "real_time": 1833455,
      "cpu_time": 306537,
      "time_unit": "ns",
      "Wall clock": 2,
      "Wall clock_max": 6,
      "Wall clock_min": 2
    }
```
1) Should I consider real or cpu time? How the time is measured in case of GPU? Is it only the kernel computation time or does it also includes CPU to GPU and GPU to CPU  memory transfer time aswell? In case of NEON benchmarking, cpu time resemblances the actual performance of the workload  ofcourse. But I am confused in case of GPU benchmarking.

The cpu_time is extremely less (less is better I know) in case of CL benchmarking than NEON benchmarking. However, I was not expecting such high performance gap for smaller matrix size and batch size=1. For the above matrix size, The real and cpu time respectively is 4646443 ns    2165464 ns in case of NEON benchmarking.

**Comment by mo-morikawa** [comment]
I too find similar numbers, and have a few questions: 

1. Are "real_time" and "cpu_time" the times consumed for all 10 iterations, or a single iteration?
2. What is the unit for Wall clock, Wall clock_max and Wall_clock min?

**Comment by AnthonyARM** [comment]
`real_time` and `cpu_time` are automatically measured by Google benchmark whereas the `Wall clock` are measured by our test and exclude the `configure` call.

Also, `Wall clock` excludes the fastest and slowest run and average the others. (Which is why it's different from the Google benchmark times)

This is because in some cases the first run is up to twice as long as the following ones because of the weights reshaping, but in a real application the weights would be stored reshaped therefore this overhead wouldn't occur.

**Comment by AnthonyARM** [comment]
@mo-morikawa 
1. Single iteration, but they're an average of all the runs (Whereas wall clock excludes the fastest and slowest)
2. Wall clock is in ms. (Unfortunately the JSON file export these values as integers instead of floats, but numbers in the console should be in floats, this will be fixed once we switch to our own framework for benchmarking)

**Comment by GeorgeARM** [comment]
Dependency of goolge benchmark was removed in 17.09 release. Closing issue. Reopen if needed.
