### ISSUE TITLE
is batch mode supported in V17.05 ?

### ISSUE THREAD

**Issue by joel-mi** [ARM-software/ComputeLibrary#185]
From the alexnet example provided with V17.06, we understand that batch mode is supported in this version.
Is it also supported in V17.05 ?

Thanks

**Comment by AnthonyARM** [comment]
Yes, it should be.
However please note that while it's functional the performance is currently not great for OpenCL: OpenCL only supports 3D workloads and therefore we used to slice the workloads  in 3D slices however we noticed that in several cases this resulted in a lot of very small kernels being enqueued which killed the performance.
We're in the process of changing that so that higher dimensions are collapsed in the 3rd one and therefore we only need to enqueue 1 kernel.

**Comment by GeorgeARM** [comment]
Closing. Reopen if needed.
