### ISSUE TITLE
An efficiency problem

### ISSUE THREAD

**Issue by wonderzy** [ARM-software/ComputeLibrary#191]
Hi，I tested the NEDirectCovolutionLayerKernel.cpp and found that when the input channel and output channel goes bigger, the efficiency goes worse, about twice slower than OpenBlas, I tested two convolution kernels with no padding

>    input                        kernel                     stride                ACL                    OpenBlas
>        5x5x48                 3x3x48x64                         1                   0.46ms                                           0.34ms
>        3x3x64                 3x3x64x128                       1                   0.46ms                                           0.25ms

This really costs too much time and I don't know why?I guess the efficiency goes worse when input image goes smaller and channel goes bigger. Right?

**Comment by morgolock** [comment]
Hi, 

Did you compile the library with debug = 0 ?
What stride values did you use for this test?
What device are you using for running the test?

**Comment by wonderzy** [comment]
Yes.I use this scons Werror=0 -j8 debug=0 asserts=0 neon=1 opencl=0 os=linux arch=armv7a
Stride has been mentioned above as 1.
Test on Nvidia-TK1

**Comment by morgolock** [comment]
Can you please post the OpenBLAS code you use as baseline?

**Comment by wonderzy** [comment]
```
void Blas_GEMM_Float(float *pDst, float *pWeights, float *pData, int M, int K, int N)
{
	openblas_set_num_threads(1);
    float alpha = 1.0;
    float beta = 0.0;
    cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, M, N, K, alpha, pWeights, K, pData,N, beta, pDst, N);
}
```

**Comment by AnthonyARM** [comment]
That's because for 3x3 and 5x5 direct convolution is probably used in OpenBLAS whereas at the moment we use im2col + GEMM for everything which is more effective for larger matrices but has an overhead too high for small ones on NEON. (We've added [NEDirectConvolution](https://arm-software.github.io/ComputeLibrary/v17.06/classarm__compute_1_1_n_e_direct_convolution_layer.xhtml) in the last release, you can already give it a go)
Anyway, we're currently still working on adding new features to the library and once it's functional we will start the optimisation work, so it's still going to take a bit of time before we catch up with the other libraries.

**Comment by wonderzy** [comment]
So do you mean NEConvolution is better for small image and NEDirectConvolution for big image?

**Comment by AnthonyARM** [comment]
It's not about the image size, it's about the Weight size: if your weights are 1x1, 3x3 (We'll add 5x5 later) then DirectConvolution should be faster for NEON.
I don't think we've ever seen images networks with 3x3 or 5x5 images (That sounds too small to do anything useful), do you have an example of one ?

**Comment by wonderzy** [comment]
I just use the DirectConvolution all the time.
I don't mean the input image for the network, but for the later conv layer, which cost much time in mine network, the 3x3 shows not good.
