### ISSUE TITLE
Accessing raw elements of CLTensor faster

### ISSUE THREAD

**Issue by nevenp** [ARM-software/ComputeLibrary#197]
Is there a faster way to access CLTensor elements? I followed this tutorial: https://arm-software.github.io/ComputeLibrary/v17.04/index.xhtml#S4_6_4_working_with_objects, but it is way to slow for very large tensors. I have float input array with raw data. First, I have to fill the input CLTensor with that data, do the convolution, and afterwards extract the data again from output CLTensor to float output array. Can I just give pointer of float input array with raw data to CLTensor and the same way extract float array from output CLTensor or something similar which is fast as well?

**Comment by AnthonyARM** [comment]
You can't just use an arbitrary pointer, the allocation must be accessible from the GPU side.

What you could do ismap the CLTensor and load the weights directly from your file into the tensor (No need to create a "float input array" first)
Same at the end: you can just map the final buffer and read from the mapped memory, instead of copying to a float array. (Basically both at the beginning and end you should be able to just go from file to CL memory and then from CL memory to file, you shouldn't need to allocate any extra array).

**Comment by nevenp** [comment]
Yes, but what if I have stream of raw data stored in float arrays and that needs to be processed in real time? Loading the data in CLTensor is bottleneck in that case.
