### ISSUE TITLE
something wrong inupdate_window_and_padding

### ISSUE THREAD

**Issue by sundw2014** [ARM-software/ComputeLibrary#21]
I have a piece of code like this:
```
NEActivationLayer activation;
activation.configure(input, output, activation_info);
activation.run();
```
I found that if the shape of ```input``` is [14,14,192], it will failed with a output like this:
```
ERROR in run src/core/NEON/kernels/NEActivationLayerKernel.cpp:204: This kernel hasn't been configured. Resource temporarily unavailable
```
But if the shape of ```input``` is [16,16,192], everything will be OK.

I found that it crashed because of an assert which says that
```
    ARM_COMPUTE_ERROR_ON_LOC_MSG((kernel->window().x().start() == kernel->window().x().end()) && (kernel->window().x().end() == 0),
                                 function, file, line,
                                 "This kernel hasn't been configured.");
```
After tracing with gdb, I found that in ```ICPPSimpleKernel::configure()```, 
 ```update_window_and_padding()``` overrode ```kernel->window().x().end()``` with zero. So, the kernel will look like not configured.

Is this a bug?

**Comment by AnthonyARM** [comment]
In your piece of code it's unclear where and how you allocate your buffers, could you please give us more details ?

**Comment by AnthonyARM** [comment]
We've tried to run the following code and it seems to work:
```cpp
    Tensor input;
    Tensor output;

    const TensorShape shape(14U, 14U, 192U);

    input.allocator()->init(TensorInfo(shape, 1, DataType::F32));
    output.allocator()->init(TensorInfo(shape, 1, DataType::F32));

    NEActivationLayer activation;
    activation.configure(&input, &output, ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU));

    input.allocator()->allocate();
    //TODO: Fill the input's content
    output.allocator()->allocate();

    activation.run();
```

**Comment by sundw2014** [comment]
Hi @AnthonyARM ,
I found that if I call the ```allocate()``` function before ```configure()```, it will crash.

The following code crashed.
```
    input->allocator()->allocate();
    output->allocator()->allocate();
    activation.configure(input, output, ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU));

    activation.run();
```
The following code worked.
```
    activation.configure(input, output, ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU));
    input->allocator()->allocate();
    output->allocator()->allocate();

    activation.run();
```
I have not got how to use ```Tensor``` properly. ^_^!

This is the complete test code
```
    const TensorShape shape(14U, 14U, 192U);

    Tensor *input = new Tensor();
    input->allocator()->init(TensorInfo(shape, Format::F32));

    Tensor *output = new Tensor();
    output->allocator()->init(TensorInfo(shape, Format::F32));

    NEActivationLayer activation;
    activation.configure(input, output, ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU));
    input->allocator()->allocate();
    output->allocator()->allocate();

    activation.run();
```

**Comment by mpflanzer** [comment]
When you call `allocate` before configuring the function the tensor by default will be allocated with no padding. The ActivationLayer function tries to process 16 elements at once (in X direction) but since your tensor is smaller the end of the window is automatically reduced to prevent invalid memory accesses. In your case it is reduced all the way down to zero which later triggers the assertion. We will add a better error message to indicate the problem.

To use the ActivationLayer function your options are:

- to set the padding manually before allocating the tensors (`TensorInfo::extend_padding(PaddingSize)`),
- to use auto padding which will be large enough to run any function but will allocate unnecessarily much memory for many functions (`TensorInfo::auto_padding()`, not recommended) or
- to allocate the tensors after configuring the functions. In that case the function will update the padding according to their needs. But this can only be done if the tensors are not already allocated.

**Comment by sundw2014** [comment]
Cool! Thank you all.
