### ISSUE TITLE
Memory management

### ISSUE THREAD

**Issue by nevenp** [ARM-software/ComputeLibrary#211]
I have very large neural network. I instantiate all layers (CLConvolutionLayers, CLPoolingLayers, CLActivationLayers), weight and bias tensors, and input and output tensors for each layer. I try to run it on Samsung Galaxy S7 and somewhere in the middle of the configuration part of the neural network, the application crashes. I can't see any warning or error log. Is it possible that mobile phone's GPU is full, so it just silently kills the application?

Edit: This error occurs: E/OpenGLRenderer:   saveGfxinfoFileDisabled enabled

**Comment by AnthonyARM** [comment]
Yes, it's possible that your phone runs out of memory.
You should have some messages in `dmesg` and `logcat` though which tell you your application was killed.

We're working on improving memory management so that you don't need to allocate an entire network upfront anymore which hopefully will solve your issue.
