### ISSUE TITLE
What is parameter:new_points_estimates in CLOpticalFlow function means?

### ISSUE THREAD

**Issue by zazd** [ARM-software/ComputeLibrary#212]
Hi,
I want to run opticalFlow using OpenCL.  It seens that this is a LK-based optical flow,
but I do not know the parameter :const ICLKeyPointArray *new_points_estimates in this function means?
Need some help , thanks!

**Comment by steniu01** [comment]
Hi, it is an array of estimated new key point positions on what is the output key points.
When the flag use_initial_estimate is set, at the max level of pyramid, it is  going to start search from the positions given by the new_points_esitmates array, otherwise, it is going to start from the position given by the old_points array.

**Comment by zazd** [comment]
@steniu01 This means if I set the flag use_initial_estimate to false, it will just use the old_points array as input to search but not new_points_esitmates array, and new_points_esitmates array will be hidden，right？

**Comment by steniu01** [comment]
@zazd, that is correct. However, since new_points_estimates is not optional in our implementation, you will hit assertion in debug mode if you pass the new_points_esitmates as nullptr. You can however pass the new_points_estimates pointer to the old_points array and set the flag to false if you don't want to use it.

**Comment by zazd** [comment]
@steniu01 Thank you for you help.

**Comment by zazd** [comment]
@steniu01 hi, I get the information that OpticalFlowLK using NEON in ARM Compute Library is about 1.5x~2.0x faster than OpenCV. But in my test, I can not get this results, even it cost much more time than OpenCV in single thread and mul-thread. My test device is SamSung G6 with Exynos 7420.
The method I use in ARM Compute Library:
1. calculate Guassian Pyramid using NEGaussianPyramidHalf.
2. calculate OpticalFlow using NEOpticalFlow.
and than compare with OpenCV calcOpticalFlowLKPyr function with same parameters.
I am sure I compile the project with  NEON.
Could you give me some suggestions for why these happened ?
Thank you for you help.
