### ISSUE TITLE
Using SubTensor in a Kernel

### ISSUE THREAD

**Issue by ymotola** [ARM-software/ComputeLibrary#218]
Hi,

I'm am trying to run a kernel with only part of an Image.
I'm sending an Image SubTensor to "NEMinMaxKernel" but I get a wrong answer.
I'm comparing it to cv::minMaxIdx with a sub matrix.
Here is my code:
`
    arm_compute::Coordinates coords(0,0,0);
    arm_compute::SubTensor subImage(image, arm_compute::TensorShape(100, 100, 1), coords);

    int32_t origMin, origMax;
    mMinMaxKernel.configure(&subImage, &origMin, &origMax);
    mMinMaxKernel.run(mMinMaxKernel.window());

    cv::Mat buff = cv::Mat(height, width, CV_16S, image.buffer());
    cv::Mat subBuff = buff(cv::Rect(0,0,100,100));
    double cvmin;
    double cvmax;
    cv::minMaxIdx(subBuff, &cvmin, &cvmax);
`
Am I declaring the SubTensore wrong?
Thanks

**Comment by GeorgeARM** [comment]
Hello @ymotola ,

Unfortunately, at the moment we don't support extraction of subtensors spatially, meaning subtensors should have the same width and height with the parent tensor. We know that being able to extract subtensors spatially is an important feature and will work to add support for this in the future. The reason that is not supported is due to padding and access pattern considerations that we have to account that apply only spatially.

George

**Comment by AnthonyARM** [comment]
George is right, this is not officially supported, you could do it by abusing the API and pretending the image was the size of your ROI and the rest was just padding. However because the rest of the image would be considered padding then it might get overwritten by some kernels which is why we don't currently allow it. But I guess if you don't care about the source image and with a bit of hacking it might work.

**Comment by ymotola** [comment]
I understand, thanks.
Do you have any other idea on how to send only part of an image in a kernel? 
Should I copy the data to a smaller image? If so what is the most efficient way to do it?

**Comment by morgolock** [comment]
Hi @ymotola 

You could try copying the values you need from the source image to a new tensor, please take a look at the link below in the documentation discussing how to use execute_window_loop and windows to copy data to and from tensors.

https://arm-software.github.io/ComputeLibrary/v19.02/architecture.xhtml#S4_6_4_working_with_objects

Hope this helps.

**Comment by morgolock** [comment]
Will close this, please reopen if needed.
