### ISSUE TITLE
NEDirectConvolutionLayer do not support 7x7 kernel size ? 

### ISSUE THREAD

**Issue by victorygogogo** [ARM-software/ComputeLibrary#251]
NEDirectConvolutionLayer do not support 7x7 kernel size ? 

what time we can use 7x7 kernel ?

**Comment by morgolock** [comment]
Hi @victorygogogo 

7x7 is not currently supported by NEDirectConvolutionLayer.

You can see what sizes and data types the function supports in the header file:
https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEDirectConvolutionLayer.h

**Comment by victorygogogo** [comment]
why not add the function in this layer ?
I see NEConvolutionLayer too, what is the different between NEDirectConvolutionLayer and NEConvolutionLayer ?

**Comment by morgolock** [comment]
Hi @victorygogogo 

Both functions perform the same computation for a given input. The difference is the algorithm used to compute the result in each case; you could expect the direct convolution to use less memory than the other approach. 

Which one is faster? It's difficult to answer because it depends on the input values and the specific CPU you run the code. For some cases the direct approach is faster and for a different input/CPU the other approach might be faster.

**Comment by victorygogogo** [comment]
if I want to realize a 2x2 and 7x7 ，how to implementit ?

**Comment by atrah22** [comment]
It seems like DirectConvolutionLayer also doesn't support 5x5 kernel. Correct me if I am wrong.

**Comment by AnthonyARM** [comment]
As mentioned above: all the sizes that are mentioned in the header file should be supported. (So yes it should work for 5x5 FP32)

**Comment by atrah22** [comment]
Okay. Thankyou.
However, In the Benchamrk GoogleNetV1 case, DirectConvolution is shown only for 1x1 and 3x3 case.

**Comment by AnthonyARM** [comment]
That's an accident, we'll add them
