### ISSUE TITLE
Assign external OpenCL buffer for GEMM

### ISSUE THREAD

**Issue by sat8** [ARM-software/ComputeLibrary#269]
Hi 

I have gathered from this [issue](https://github.com/ARM-software/ComputeLibrary/issues/127)  that a native tensor's memory can be used subsequently within external OpenCL code. My requirement is to do the opposite (Assign an external cl_mem object to native tensor in ACL). 

My [project](https://github.com/sat8/YoloOCLInference) is a YOLO inference engine specifically for OpenCL devices and I benchmarked GEMM with ACL on ARM hardware is much better. I intend to plug ACL just for the GEMM portion of my project and hence need to assign an external cl_mem object to ACL tensor object.

Is this possible in practice and how would I go about it?

In general, it may be useful to include an 'interop' example that demonstrates the logic to plug ACL kernels
in to an external OpenCL code flow.

thnx

**Comment by GeorgeARM** [comment]
Hello @sat8,
Currently we don't an explicit way to set a memory directly as a backing memory in a tensor but will we look into it. For now there are some ways into doing so. The simplest one is to implement a new CLTensor and CLTensorAllocator or you can alter the existing CLTensorAllocator so that it can get a cl::Buffer and set it directly as a backing memory. It should be relatively easy for your needs.
Hope this helps.

**Comment by sat8** [comment]
@GeorgeARM thnx for the suggestion.

**Comment by GeorgeARM** [comment]
Added supported for importing memory to a CLTensor in 18.05. Thus closing. Reopen if needed

**Comment by Dilshodzhon** [comment]
Hello @GeorgeARM , I couldn't find any change of CLTensor in last 3 versions. Can you give me some insight how to use this new feature, pls?
