### ISSUE TITLE
ARM ComputeLibrary is slower than NNPACK?

### ISSUE THREAD

**Issue by ghost** [ARM-software/ComputeLibrary#282]
I have the code as it is written below:

    high_resolution_clock::time_point t1 = high_resolution_clock::now();
    layer1->run();
    layer2->run();
    layer3->run();
    ...
    layern->run();

    arm_compute::CLScheduler::get().sync();
    high_resolution_clock::time_point t2 = high_resolution_clock::now();

    CLTensor tensor;
    tensor.allocator()->init(TensorInfo(TensorShape(3U, 3U, 16U, 1U), 1, DataType::F32));
    tensor.allocator()->allocate();
    tensor.map();
    tensor.unmap();

    auto time = duration_cast<microseconds>( t2 - t1).count()/1e6;

I achieve worse execution time using OpenCL GPU ARM Compute Library engine than using NNPACK's CPU engine on mobile phone device (S. Galaxy S7) for the same NN architecture. Is there any obvious missing point that I am not aware of? Optimization flag or something else for mobile phone's GPU? Do you have time executions comparisons by layers between OpenCL GPU ARM Compute Library and NNPACK for CPU? I believe that GPU engine should be much more faster than CPU engine even though we talk about CPUs and GPUs on mobile phones.

**Comment by AnthonyARM** [comment]
Just a couple of things:
1) With 18.01 and previous releases for NEON you might want to manually set the number of threads used by the scheduler (Otherwise by default on big LITTLE systems it will defaults to the number total of cores rather than just the number of big cores)
2) Both NEON and CL performance should have greatly improved since this issue was open.
3) On the S8 the GPU cores are partitioned, and compute workloads can't use all the cores which is why in some cases you might not get the expected performance.

Have you tried to collect data with a more recent version of the library ?

**Comment by prnvjb** [comment]
I think because of bottleneck of copying data from cpu to gpu.
