### ISSUE TITLE
Error: Non uniform workgroup size is not supported

### ISSUE THREAD

**Issue by shenck0** [ARM-software/ComputeLibrary#289]
When executing ./examples/cl_convolution, program crash at code:
```C++
ARM_COMPUTE_ERROR("Non uniform workgroup size is not supported!!");
```
in function CLKernelLibrary::create_kernel.
I'm running cl_convolution on a Mali T760 device. According to Mali GPU OpenCL Developer Guide 3.2, T760 is a Midgard arch GPU and suppose to have cl_arm_non_uniform_work_group_size extension.
Then I modified the code mentioned in #104  :
> mo-morikawa commented on 16 May
> Many thanks, that fixed the problem. In my case, it was -cl-std=CL1.1.

and the cl_convolution shows 'Test passed'.
Here is my questions,
1. Did 'Test passed' means the convolution calculated correctly?
2. It seems function non_uniform_workgroup_support() return false on my device. Is this caused by the improper OpenCL driver I'm currently using? If so, how to enable this extension or get correct driver.

Any hint will be appreciate!

**Comment by AnthonyARM** [comment]
Just to clarify: adding `-cl-std=CL1.1` on top of  `cl_arm_non_uniform_work_group_size` seems to have fixed the issue for you ? (If that's the case we might want to make that the default)

1. No, it just means it ran. If you want to make sure everything works fine you should run the `arm_compute_validation` test suite.
2. Might be due to the driver being too old. Do you know what version of the driver you have ? What platform are you running on ?
Unfortunately the driver update can only come from your device manufacturer as there is some platform integration work required to make it work.

**Comment by shenck0** [comment]
@AnthonyARM 
Thanks for your reply. 
In my case, replacing `-cl-arm-non-uniform-work-group-size` by `-cl-std=CL1.1` (in function `CLKernelLibrary::create_kernel`) makes `examples/cl_convolution` running without error. And I'm trying to run the validation tests to ensure that convolutional results are correct.
The platform I'm using is [this](https://en.wikipedia.org/wiki/Rockchip_RK3288) and I will check for possible driver update.

**Comment by AnthonyARM** [comment]
I guess you might be lucky that this particular example doesn't require the extension but I would expect other tests to fail.
Which device is it exactly?
If it's a Firefly you could try updating the driver : https://developer.arm.com/products/software/mali-drivers/user-space

**Comment by GeorgeARM** [comment]
Closing issue. Seems your driver version does not support `-cl-arm-non-uniform-work-group-size`. Reopen if needed.
