### ISSUE TITLE
ACL mandates libOpenCL.so and Mali OpenCL has reached End-of-Life

### ISSUE THREAD

**Issue by santo4ul** [ARM-software/ComputeLibrary#291]
Hi, 

I'm using the latest version of ACL V17.10. There is a stub libOpenCL.so and ACL mandates to use a real libOpenCL.so.

However, the Mali libOpenCL.so is not maintained or supported by ARM anymore. Even the SDK is not available for download online. This has been confirmed by ARM based on [this](https://community.arm.com/graphics/f/discussions/9417/mali-opencl-sdk-not-found) discussion on community.arm.com

I am trying to use ACL on Android and unfortulatenly couldn't find OpenCL source to compile or any libOpenCL.so library to be used with Android.

This is currently a blocker.

Is there a workaround? Could someone upload the libOpenCL.so (arm64) and other relevant libraries for Androis for users so that it isn't a blocker?

Thank you.

Regards,
San

**Comment by AnthonyARM** [comment]
I think there is a bit of confusion:
- Yes, the OpenCL SDK has been discontinued (Mainly because you have a lot of good quality OpenCL tutorials on internet to get started) but it never contained any OpenCL driver so this doesn't change anything.
- We provide a stub library to allow you to build the library and your application without having to pull any file from your device. You then just need to upload your application and the Compute Library binaries to your device and the real OpenCL driver will automatically be picked up at runtime.

If your device doesn't have OpenCL then you need to ask your device manufacturer: each device requires some integration work, Arm cannot provide generic drivers that will work everywhere, they have to come from the manufacturer.

Alternatively, you can find a few userspace drivers here: https://developer.arm.com/products/software/mali-drivers/user-space

**Comment by santo4ul** [comment]
Agree. Thanks for your inputs. I'll check with the SoC vendor.

Moreover, I got input from ARM developer community that the libGLES_mali.so may also have the OpenCL related symbols. 

Thanks again!
