### ISSUE TITLE
Tensor concat/Split

### ISSUE THREAD

**Issue by WenguoLi** [ARM-software/ComputeLibrary#297]
How to concat 2 tensors to 1?

How to Split  a tensor to 2 ones?

**Comment by WenguoLi** [comment]
How to do Concat layer and Split layer of Squeezenet ? 

Thanks!

**Comment by GeorgeARM** [comment]
We have the `SubTensor` feature for doing so in order to avoid copying data around.
`SubTensor` works only if you split/merge across depth or any higher dimension.
Unfortunately it does not work if you want to create a `SubTensor` with different spatial dimensionality from the parent `Tensor`.
e.g. Look [here](https://github.com/ARM-software/ComputeLibrary/blob/master/tests/networks/AlexNetNetwork.h#L84) for the AlexNet example that uses `SubTensors` for the grouped convolution.

**Comment by GeorgeARM** [comment]
Closing issue. Reopen if needed. Subtensors could be used for concat/split. For depth concatenation `NEDepthConcatenateLayer` and `CLDepthConcatenateLayer` is another option but it involves copying the input tensors to the output one.
