### ISSUE TITLE
graph api

### ISSUE THREAD

**Issue by hexiangquan** [ARM-software/ComputeLibrary#335]
use graph api is not convient to  cascade network . input accessor and output accessor is private member in class graph .   and multi-output also have some peoblem  ? any update in next release ?

**Comment by AnthonyARM** [comment]
We're mainly developing the Graph API as a tool for our internal testing, which means we add features as we go when we need them but we're not currently planning on turning it into a product which is why you might still find some features missing.
Work is on-going to integrate the Compute Library in higher level frameworks though, so soon you'll be able to use more complex frameworks to build your networks rather than the rather low level API of the Compute Library.

**Comment by AnthonyARM** [comment]
Issue not clarified, closing.
