### ISSUE TITLE
graph_alexnet has high performance gap between with and without labels.txt file! 

### ISSUE THREAD

**Issue by atrah22** [ARM-software/ComputeLibrary#381]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform: Samsung Galaxy S8 (Exynos SoC)

**Operating System: Android 7.0

**Problem description:
The performance gap is huge when running graph_alexnet with labels.txt & input image and without labels.txt & input image.

cmdline:
Performance = 109ms (graph_alexnet_aarch64 2 /data/local/tmp/ACL/CNN ./go_kart.ppm ./labels.txt)
Performance =   40ms (graph_alexnet_aarch64 2)

I measured "example.do_run" function from  ./utils/Utils.cpp file. I included a for loop to run only the forward propagation 20 times. The Performance metric is the average performance for 20 runs. The change in Utils.cpp is below:

       clock_t start2 = clock();
       example.do_run();
        clock_t stop2 = clock();
        double dif2 = (double)(stop2-start2) * 1000.0 / CLOCKS_PER_SEC;
        accum2=accum2+dif2;
        }
        double dif1 = (double)(stop1-start1) * 1000.0 / CLOCKS_PER_SEC;

Without giving weight data and input image the graph_alexnet creates random data and the performance overhead is in the do_setup function. In do_run function, it runs the whole Alexnet grpah irrespective of input image and weight data arguments. In case of labels.txt argument, the only difference is the sorting function for the top 5 predictions. 

However, the the performance is gap is more than 2x when input image, weight data and labels.txt files are given as argument vs no input data & labels.txt file!

Why the performance gap is so high? Is it a Bug?

**Comment by AnthonyARM** [comment]
1) When you read the labels back the output tensor needs to be mapped and copied (This might be the reason for the overhead too)
2) Did you run the tests more than once ?
3) Do you exclude the first run from your measurements ?

The reason I'm asking is
1) You could check this by passing an accessor to the output tensor even when processing random data
2) Since 18.03 when the CLTuner is used the LWS table is saved to file at the end of the run (acl_tuner.csv) and other executables will automatically pick it up after that (Regardless of whether or not the CLTuner is enabled), which means your second run will actually not do any tuning as all the values will already be in the file
3) The first run is really slow because the library is trying a wide range of LWS, so because of (2) it might be that the first run will have a very slow run followed by fast runs but not enough to average it out, while the second run will pick up the csv file and therefore not do any tuning and therefore end up with only fast runs.

Make sense ?

**Comment by atrah22** [comment]
Hello @AnthonyARM ,
Thankyou so much for quick reply. I do understand that the 1st run takes long time and its therefore excluded.
2) & 3)  Yes I run for 20 iterations each time (example.do_run) and the average performance is for the next 20 runs. The first 20 runs tunes and specially the first run takes long time (few seconds). After that I run again 20 runs and take the average of that. So the next 1, 2, and 3 (the reason I'm asking) is understandable and I understood it while evaluating performance.

1) So now my question remains the same and the probable answer is 1 (When you read the labels back the output tensor needs to be mapped and copied (This might be the reason for the overhead too). Isn't the overhead too high? its higher than the actual CNN network computationby more than 2x (I see similar performance gap incase of inception-v3 as well). For a real test case scenario/ CNN application, the overhead will affect the performance by large margin. 

2) Will there be any optimization regarding the output tensor mapping and copying? The output read & sorting overhead is very low in case of other vendor specific CNN SDKs.

**Comment by AnthonyARM** [comment]
I guess the other thing is: I assume you're loading the input image from file, so that's probably quite slow too.
At the end of the day the only thing you can do to speed things up is to only keep the big cpu cores online and set them to performance mode but to fair cache maintenance and i/o accesses are independent from the library so I don't see how other frameworks can speed those up.

**Comment by atrah22** [comment]
Thankyou for the reply.
1) The input image loading overhead is quite less (do_setup funciton)
2) My concern is regarding the do_run function. A complete run including input image and prediction on S8 (Qualcomm SoC) using SNPE shows that the inference performance is slightly lower than the forward propagation meaning the input loading and output labels loading performance overhead is insignificant. I understand, maybe thats not the case with ARM and/or Exynos SoC.

BRs,
Atul

**Comment by AnthonyARM** [comment]
You set the accessor in do_setup but the accessor gets called every time you call `graph.run()` because usually you would want to detect a different image for each run.
I don't know how SNPE works, but are you sure you're reloading the image from file at every run ? Maybe there is some kind of mechanism to cache the image ?
The graphs we provides are only examples, that's why they don't contain anything fancy in terms of loading / storing images.

**Comment by mpekatsoula** [comment]
Closing, reopen if needed.
