### ISSUE TITLE
Alexnet non-graph classification gives wrong classification result

### ISSUE THREAD

**Issue by pcub** [ARM-software/ComputeLibrary#389]
I am testing alexnet (https://github.com/ARM-software/ComputeLibrary/blob/master/tests/networks/AlexNetNetwork.h) with cat image (https://github.com/BVLC/caffe/blob/master/examples/images/cat.jpg).
in source code, expected label is 281 (as seen in https://gist.github.com/yrevar/942d3a0ac09ec9e5eb3a) and which corresponds to  cat category.
However, when I run the alexnet example above, classified label is not 281.
**Note:** input (e.g., cat.jpg) image was resized to 227x227x3 and saved as npy format.
did anyone get 281 from alexnet classification results?
is it possible to share python script for generating npy files?

**Comment by GeorgeARM** [comment]
Hello @pcub,
Can you try the graph_alexnet example instead? You can pass a ppm directly to it

**Comment by pcub** [comment]
graph_alexnet works as expected.
what do you mean "pass a ppm directly to it"?
non-graph alexnet implementation takes npy as input image.

**Comment by GeorgeARM** [comment]
@pcub I meant that in the graph example you can pass a ppm directly to it and not a npy binary.
Now in the non-graph implementation you should read an image in python translate it in planar format instead of interleaved and dump it as a continuous memory block to a npy file.
ACL supports NCHW format so make sure your input is in this format.

**Comment by pcub** [comment]
thank you @GeorgeARM , However, I am not clear about your comment. Is it possible to get more specific information. in non-graph alexnet implementation, input image is 227x227x3. how to save this image in npy format?
