### ISSUE TITLE
The question of OpenCL with Tuner in graph examples

### ISSUE THREAD

**Issue by nadongguri** [ARM-software/ComputeLibrary#392]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v18.03 Build options: {'embed_kernels': '1', 'os': 'linux', 'opencl': '1', 'neon': '1', 'build_dir': 'build_d0_a0_n1_c1_m1_t1_e1', 'arch': 'armv7a', 'asserts': '0', 'debug': '0', 'openmp': '1', 'cppthreads': '1', 'Werror': '1'} Git hash=unknown

**Platform:** Tizen

**Operating System:** Linux

**Problem description:**
Hi, I've run graph_alexnet and graph_googlnet with OpenCL Tuner (2).
It took both very long time to create an acl_tuner.csv file and
There was no performance difference in case of graph_alexnet, but there was some improvement in performance in case of graph_googlnet.

AVG time of graph.rum() from 2nd to 10th (ms)

example |  OpenCL | OpenCL with Tune
------------|--------------|--------------------------
graph_alexnet |  366 | 368
graph_googlenet | 693| 605 

What I'm wondering is
How far can we expect to improve the performance using Tuner?

Thanks.

**Comment by gmiodice** [comment]
Hi @nadongguri ,

could you check if your GPU frequency is constant for the whole duration of your tests? The OpenCL tuner takes a lot of time because it uses a brute force approach to look for the optimal LWS to use for each tunable kernel.
However in order to have reliable results by means of the OpenCL tuner the GPU frequency must be constant during your tests.
You could check every second the GPU freq using a command like the following one:
```bash
while true; do cat /sys/devices/platform/e82c0000.mali/devfreq/gpufreq/cur_freq; sleep 1; done
```
If the GPU freq. changes, with high probability your kernels will not tuned in optimal manner and you could have worst performance than before.

In the end every time you want to tune your network, you should remove (or rename) the file acl_tuner.csv. If you do not remove that file, ACL will pick it up and use the results of tuner stored in that file.

Let us know if this can help you,
Gian Marco

**Comment by nadongguri** [comment]
Dear @gmiodice,

thanks for the reply.
I've checked the freq of GPU is constant and (DFS is disabled) the GPU freq is 400Mhz.
So, is the performance improvement rate according to OpenCL tune different for every graph example?
 (Based on my test result, graph_alexnet and graph_googlnet shows the difference.)

Regards,
Dongjin.

**Comment by mpekatsoula** [comment]
@nadongguri 
CLTuner is able to find the optimal LWS for your kernel in order to improve the performance. Since each graph example/network uses different combination of kernels the improvement will vary.

**Comment by chiraggirdhar95** [comment]
@mpekatsoula for some graphs CLTuner takes a lot of time to find the optimal LWS for kernels. Can you suggest a way to reduce the complexity?

**Comment by mpekatsoula** [comment]
Hi @chiraggirdhar95 

There is an improved CLTuner coming out in our next release. You can also checkout our public development repository here: https://review.mlplatform.org/#/admin/projects/ml/ComputeLibrary

**Comment by chiraggirdhar95** [comment]
@mpekatsoula thanks for the reply.
