### ISSUE TITLE
Mali-G51 compute capability

### ISSUE THREAD

**Issue by op21beyond** [ARM-software/ComputeLibrary#398]
Doc from ARM site says G51 MP3 has 4 execution engines and MP4 has 5.
Then, does it means we can expect 6/4 times higher computing capability from MP4 than MP3? Not 4/3?

**Comment by op21beyond** [comment]
correct. 6 engine for MP4

**Comment by AnthonyARM** [comment]
This is a hardware related question, this is not related to the Compute Library, please try asking on http://community.arm.com

**Comment by op21beyond** [comment]
@AnthonyARM 
Hello. I got an answer from ARM Comunity site. 
MP3 has 1 execution engines for a small shader core and 3 engines for a big shader core.
G51-MP3 GPU provides 2 Open-CL compute_units.
Then, here is my question.
cl_tuner seems not making much differences in my G51-MP3 platform.
Does cl_tuner try to tune for this kind of a big and small compute unit combination?
or just try to tune for either the big unit orthe small unit?

**Comment by AnthonyARM** [comment]
cl_tuner currently uses a brute force approach: it will run the same kernel in a loop trying different local workgroup sizes and will remember which one was the fastest for the subsequent runs. (It doesn't make any assumptions about the GPU itself).

Please make sure the GPU frequency is static when running the tuner because if it changes during the tuning phase then the numbers stored will be wrong and it won't go faster as a result.
Could you explain how you used the tuner ? Was it using one of our graph examples ?
