### ISSUE TITLE
Canny kernel ACL output different for GPU and NEON - ACL 17.10 - request for inputs

### ISSUE THREAD

**Issue by vinithsrvv1** [ARM-software/ComputeLibrary#424]
Hi Sir,
When executing ACL canny kernel for the sample image of color bars, NEON and GPU outputs are coming different. Can you kindly explain the reason for this? 

Version : 17.10 

Attaching the input images, generated output images , sample test app for reference . Please change the extensions of following files to .rgb when executing 

colorbars_640x480_I444.txt - input image 
canny_out_neon_SA.txt - NEON output image 
canny_out_gpu_SA.txt - GPU output image 

Thanks,
Vinith 
[neon_canny_test.txt](https://github.com/ARM-software/ComputeLibrary/files/1893921/neon_canny_test.txt)

[cl_canny_test.txt](https://github.com/ARM-software/ComputeLibrary/files/1893922/cl_canny_test.txt)

[colorbars_640x480_I444.txt](https://github.com/ARM-software/ComputeLibrary/files/1893924/colorbars_640x480_I444.txt)
[canny_out_gpu_SA.txt](https://github.com/ARM-software/ComputeLibrary/files/1893925/canny_out_gpu_SA.txt)
[canny_out_neon_SA.txt](https://github.com/ARM-software/ComputeLibrary/files/1893926/canny_out_neon_SA.txt)

**Comment by manjunathahg** [comment]
Hi team, 
any update on the above issue?

**Comment by AnthonyARM** [comment]
There is no guarantee that outputs will be identical (Because of the difference in the number of threads running on a GPU vs CPU), however both implementations are guaranteed to match a single threaded C implementation for 90+ % of the edges. (We haven't released the validation test for this yet, but we have it internally and it didn't highlight any issue with either implementations, the test will be released in the 18.08 release)

**Comment by mpekatsoula** [comment]
Closing, reopen if needed.
