### ISSUE TITLE
How to port ACL library to android hal?

### ISSUE THREAD

**Issue by liupanpan** [ARM-software/ComputeLibrary#427]
Hi Sir:
I have build arm_compute_core-static.a, libarm_compute-static.a libraries. And porting them to android os.
But when i use acl api in the android hal, there are some std undefined reference errors. It maybe that acl need gnustl lib, but android os has no the link library.

**Comment by AnthonyARM** [comment]
Hi,
If you're going to link the Compute Library statically then you need to build it from inside your Android tree using the same toolchain as your other libraries.
You could also just use it as a shared library (The documentation recommends linking statically on Android because of a bug in old versions of the Mali driver, but if you've got a fairly recent version of the driver this shouldn't be an issue)
