### ISSUE TITLE
Maxpool padding issue 

### ISSUE THREAD

**Issue by uu-praveeng** [ARM-software/ComputeLibrary#43]
Hi,

Im implementing the Alexnet using the armcomputelib for Neon.For the last Maxpooling(13,13,256) 
the output is not as expected with the other platforms(GPU).

For Maxpooling the previous layer output is Relu Layer(output actual dimension:13,13,256 output Padded dims by armcompute: 16,13,256) in which there is padding of 3 floats(hence 16 width) in row wise .Im feeding the same tensor to Maxpooling with configuration as below

PoolingLayerInfo(PoolingType::MAX, 3,PadStrideInfo(2,2,0,0,DimensionRoundingType::FLOOR))

Can you check what could be the issue for this.
Im attaching the input ,output,ref_output for  maxpooling in the below google drive link.

https://drive.google.com/open?id=0B8m_q7acVVbbTl9kbGJEUkVVN3M

Note: I'm using the latest version of armcompute.

Thanks,
G.Praveen.

**Comment by sundw2014** [comment]
I encountered the same problem. Is there any method to set the padding of a tensor to zero?

**Comment by AnthonyARM** [comment]
@sundw2014 : You can force the padding size to 0 by allocating your tensor before calling your function's configure method.

**However**, if there is no padding available then the execution window will be shrunk to accommodate the memory alignment required by SIMD instructions which means some of the elements will not be processed.

While this might not be an issue for computer vision algorithms (it just means border pixels are not processed) it's likely to lead to a completely wrong result for neural network functions.

More details in the [documentation](https://arm-software.github.io/ComputeLibrary/v17.04/index.xhtml#padding)

Hope this helps

**Comment by sundw2014** [comment]
@AnthonyARM , Thank you!
I'm so sorry I didn't make myself clear. What I mean is to set the content of the padding to zero instead of removing the padding.

**Comment by AnthonyARM** [comment]
Oh I see, sorry.

The padding is filled automatically by the [NEPoolingLayer](https://arm-software.github.io/ComputeLibrary/v17.04/classarm__compute_1_1_n_e_pooling_layer.xhtml#details) function using [NEFillBorderKernel](https://arm-software.github.io/ComputeLibrary/v17.04/classarm__compute_1_1_n_e_fill_border_kernel.xhtml)

And you can see it in the code [here](https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/NEON/functions/NEPoolingLayer.cpp#L40)

I see the issue was closed: did you both manage to make your code working or is there still an issue we need to investigate ?

**Comment by uu-praveeng** [comment]
From my side there is no issue except for issue 47. 
One more thing Is there leaky relu implementation in the Activation Layer I dint find one in ARM-Compute.
