### ISSUE TITLE
Difference between ARM Compute Library and ARM NN - Info needed

### ISSUE THREAD

**Issue by mkamrao** [ARM-software/ComputeLibrary#462]
Hi

I have come across ARM NN: https://github.com/arm-software/armnn

Could you please give some idea on whether it is same as ARM Compute library and what are the differences/similarities.

Basically, I would like to evaluate whether we can use ARM Compute Library OR ARM NN.

Any inputs in this regard would be really helpful.

Thanks in advance.

Kamrao

**Comment by mkamrao** [comment]
ok. Thank you. I shall take a look at this.

Kamrao

**Comment by gmiodice** [comment]
Thanks @mkamrao . I close the ticket but feel free to open another one if you have any further question

**Comment by prateethvnayak** [comment]
Hi,

Can anyone point me to as a Beginner guide to ArmNN ? I am also confused whether to build the network using the basic building blocks in ACL or to use the ArmNN graph API. 

Thanks

**Comment by ManubARM** [comment]
Hi @prateethvnayak ,
It depends on the degree you want to tweak the network. We suggest ArmNN because developed for an higher level of abstraction. 

Here the link of the repo: https://github.com/arm-software/armnn
Ask there for a guide, they will probably know better where to redirect you.

Also please open a new issue next time

Thanks

**Comment by prateethvnayak** [comment]
@ManubARM Thanks for the quick reply. I just replied here since it was on Similar lines rather than opening a new issue.

I am talking in terms of very basic math operations level, where I need the flexibility of playing with bit-precision for weights in the network. In that sense ACL is more suitable ? or I still could stick to ArmNN. 

Thanks

**Comment by ManubARM** [comment]
It is more difficult for us to keep track of closed issues, they just won't stand up. Feel free to reopen.

If you want to develop a network with layers already supported in ACL, go for ArmNN. You can use ACL to develop networks, but you'll find it easier with ArmNN.

If you want to create new operators or modify existing ones for research (for example), ACL. In this last case, if we find it of interest we might merge the patch. 

Manuel

**Comment by prateethvnayak** [comment]
@ManubARM 

Yes, I will be wanting to modify or add new operators for research purpose. I will stick to ACL. Will keep you posted once I have working idea.

And, next time will reopen/open a issue. 

thanks

**Comment by ManubARM** [comment]
You might be interested on out Linaro gerrit repo:
git clone https://review.mlplatform.org/ml/ComputeLibrary

In there we can review your commits so that they can stick to our conventions

Manuel
