### ISSUE TITLE
Output mismatch in NEOpticalFlow

### ISSUE THREAD

**Issue by manjunathahg** [ARM-software/ComputeLibrary#466]
**Output of 'strings libarm_compute.so | grep arm_compute_version':** arm_compute_version.embed

**Platform:** ACL NEON

**Operating System:** Linux 64 bit

**Problem description:**
Hello sir,
We are trying to execute NEOpticalFlow kernel in arm compute library on ACL NEON platform. 
We have a reference implementation of the Optical flow and we are observing mismatch in output keypoints.
However the output on ACL GPU matches with the reference output.
The stand alone code, all inputs files and logs are attached for your reference.
The input keypoints and pyaramid data are fed from text files.

Please let us know your inputs for resolving the issue.

Thank you

Code:
[neon_opticalflow.txt](https://github.com/ARM-software/ComputeLibrary/files/2118640/neon_opticalflow.txt)
Input:
[newPyramid.txt](https://github.com/ARM-software/ComputeLibrary/files/2118642/newPyramid.txt)
[oldpts.txt](https://github.com/ARM-software/ComputeLibrary/files/2118643/oldpts.txt)
[oldptsEst.txt](https://github.com/ARM-software/ComputeLibrary/files/2118644/oldptsEst.txt)
[oldPyramid.txt](https://github.com/ARM-software/ComputeLibrary/files/2118645/oldPyramid.txt)

Output:
[neon_opticalflowLog.txt](https://github.com/ARM-software/ComputeLibrary/files/2118651/neon_opticalflowLog.txt)
[Reference_output_keypoints.txt](https://github.com/ARM-software/ComputeLibrary/files/2118652/Reference_output_keypoints.txt)

**Comment by ManubARM** [comment]
Hi @manjunathahg ,
We tried your example and we can recreate the problem. Could ask you more details about your reference implementation? How do you validate it? Do you have also a tensorflow script implementation of the code?

Thanks,
Manuel

**Comment by morgolock** [comment]
Hi @manjunathahg 

Apologies for the delay in the reply.

I took a quick look at your example, the mismatches you see are due to the lack of padding in the pyramid images.

A quick way to fix the mismatches is by replacing lines 57 and 58
`aclOldPyramid.init(PyramidInfo(3, 0.5, 640, 360, Format::U8));`
`aclNewPyramid.init(PyramidInfo(3, 0.5, 640, 360, Format::U8));`

by the following code:
`const PyramidInfo pyr_info(3,SCALE_PYRAMID_HALF, TensorShape(640U,360U),Format::U8);`
`aclOldPyramid.init_auto_padding(pyr_info);`
`aclNewPyramid.init_auto_padding(pyr_info);`

I verified this running the example after making the change mentioned above, using ACL 19.05.

Hope this helps.
