### ISSUE TITLE
batch normalization and activation Relu - incorrect output for height 52, width , 66 , channels 128

### ISSUE THREAD

**Issue by abhajaswal** [ARM-software/ComputeLibrary#473]
Hi I am using ACL to implement tensorflow based Neural network.

Output of most of layers is compatible with TensorFlow.
But In case I use a openCl based batch normalization & Relu activation for a 66x52x128 size the output does not match that of tensorflow.
Is there any limitation for non-multiple of 4 input size in this case? as I could understand any other logic behind the mismatch!

COmpute library v 18.05.

Please revert

**Comment by gmiodice** [comment]
Hi @abhajaswal,

could you report the output shapes reported by ACL and TensorFlow?

Thanks

**Comment by ved27** [comment]
Same is the case here.

Output of tensor flow & ACL  is same as that of Input( width:66 , height:50 , channels : 128 , **Datatype:F32**) since the layers are batch Normalization & Relu .
(Here width and height are not multiples of 4 .)
 for the above size the output values do not match at the boundaries 

For other sizes like 208x272 , 48x64 ACL is working fine for Normalization & Relu .

Awaiting a solution,

**Comment by GeorgeARM** [comment]
@ved27, @abhajaswal can you provide more information about your test setup? Platform?  OS? Build options? How do you configure your functions and where do you allocate the tensors (provide code snippet)? There is an issue template when you create an issue, please follow the instructions there as it will help us debug the problem faster.

**Comment by abhajaswal** [comment]
I build 18.05 version using : 

scons Werror=1 -j8 debug=0 asserts=0 neon=0 opencl=1 openmp=1 cppthreads=1 embed_kernels=1 os=linux arch=armv7a

I will check once if i could share the code snippet on public domian once!

**Comment by abhajaswal** [comment]
@GeorgeARM  I have another query, is there any document regarding how much memory each ACL layer supported for NEON/CL takes?
I want to calculate the memory requirement for my trained network, will it be same as used by a tensor flow application.?

I have a memory constraint issues for GPU(500MB) /NEON(1GB) support  in my environment, So i want to analyse upto how much layers i can easy implement using ACL, without any out of memory issues(which i currently face for a larger input size image)

Also if i could get a document on how to do memory management for CL/NEON for ACL.

**Comment by abhajaswal** [comment]
I have also tried Neon Airthmetica Addition, Batch normalization and relu layer for non-multiple of 4  height width, the output is not correct at boundary pixels.
All multiple of 4 height width test cases for these layer match that of tensorflow!!!

I will not be able to share the code for it as off now.

**Comment by gmiodice** [comment]
Hi @abhajaswal,
when do you allocate the memory for your tensors? before or after the configuration of the functions?

**Comment by GeorgeARM** [comment]
Hello @abhajaswal,

I think the only reason to take incorrect results could be due to the incorrect use of the ACL API.
We test for sizes that are non-multiple of 4 thus my assumption is that you allocate your tensors before configuring your functions which leads to shrinking the execution window and as a result to not calculate the boundary pixels. Can you try with debug enabled and check if you see any errors?
The flow should be something like:
```
// Init tensors and tensor metadata (Do not allocate yet)
// Configure your functions
// Allocate tensor
```
Eitherway, without more information is too difficult to debug the issues.

**Comment by abhajaswal** [comment]
Thanks for the reply. 
I follow the same heirairchy as suggested by you 
// Init tensors and tensor metadata (Do not allocate yet)
// Configure your functions
// Allocate tensor

i will cross check again with debug on

**Comment by abhajaswal** [comment]
Issue was with accessing the input->buffer to these layers without the execute window loop, by fixing our ACL application code it got fixed. Thanks for your suggestions

**Comment by gmiodice** [comment]
Hi @abhajaswal,

thanks for reporting. We are happy to know you fixed the issue. I close this ticket but feel free to open another one if you need any further help.

Thanks
