### ISSUE TITLE
Output shape computation in CLDeconvolutionLayer

### ISSUE THREAD

**Issue by ved27** [ARM-software/ComputeLibrary#482]
Hi,

version : Computelibrary 18.05
Platform : arm7a
Operating System: linux

I have a query regarding the output tensor's shape calculation in CLDeconvolutionLater::configure(...)
The following line: 

    **auto out_dims = deconvolution_output_dimensions(input->info()->dimension(0), input->info()->dimension(1), weights->info()->dimension(0), weights->info()->dimension(1),
                                                    info.pad().first, info.pad().second, inner_border_top, inner_border_right, stride_x, stride_y);**

has arguments   inner_border_top, inner_border_right misplaced ,

where as  CLDeconvolutionLater::validate(...) has the same line correct

Kindly review this once,

Thank you,

**Comment by ved27** [comment]
Hi,

Can anyone kindly review this , so that I shall check using the Deconvolution for my network soon as possible,


Thank you,

**Comment by mpekatsoula** [comment]
Hi @ved27 ,

Indeed the arguments are misplaced. This will be fixed in the next release. Until then you can apply the fix on your code
`    auto out_dims = deconvolution_output_dimensions(input->info()->dimension(0), input->info()->dimension(1), weights->info()->dimension(0), weights->info()->dimension(1),
                                                    info.pad().first, info.pad().second, inner_border_right, inner_border_top, stride_x, stride_y);`

Thanks for reporting this

**Comment by ved27** [comment]
Hi ,

Yea, I applied it and checking the output across the reference output dumped from TensorFlow


Thank you,
