### ISSUE TITLE
Query regarding Fast math hint

### ISSUE THREAD

**Issue by ved27** [ARM-software/ComputeLibrary#508]
Hi,

I try to use fast_math with winograd convolution layer.

Can you please let me know what happens when fast_math is enabled ? A gist of how it works , and if there is any configuration for which it gives best performance ?  
Also , if the similar flag is used by any other layer?

Desperately awaiting your reply,

**Comment by morgolock** [comment]
Hi @ved27 

In Winograd, there is a loss in accuracy for kernel size 5 and data type float because of the implementation details of the algorithm. The `fast maths` flag is used mainly to ensure the user is aware of this loss of accuracy as it's required to be true for certain configurations; the `configure()` method will check that the flag is enabled for specific kernel sizes like 5.

The flag has no effect at all on the execution time and it's used only to check if the user is aware of the loss of accuracy: the user must pass `true` when the kernel size is 5.

Do not expect a dramatic speedup when passing `fast_maths = true` as this flag is only used in the way explained above.
