### ISSUE TITLE
Memory usage CL vs Neon

### ISSUE THREAD

**Issue by ved27** [ARM-software/ComputeLibrary#541]
Hi 

Platform : linux
Compute Library 18.05
arm7a

I'm trying to run graph_mobilenet.cpp example to profile the memory taken .
I profiled it running it on  CL  , while in another case with Neon .

In the two cases memory consumption with Neon is greater than that with CL. Around 8 times more.

My doubt is that , when the network is same and methods of computation in layers are same which means the allocation of additional buffers is same , why does CL ( on gpu ) code consume less memory than Neon (on cpu) code ? Is there some reason of implementation behind this ?

For ex: GEMM Convolution in openCL takes less memory than the same convolution with Neon
Is there some funda behind it ?

Thank you,
Awaiting some knowledge gain at the earliest

**Comment by GeorgeARM** [comment]
Hello @ved27,
Thank you for raising that, seems that something might have been altered in the way the memory is managed in the NEON side. We will investigate and update this issue.

**Comment by ValentinoPeluso** [comment]
According my experiments, this bug is present also in version 18.08. @GeorgeARM, might you confirm?
Thanks.

**Comment by GeorgeARM** [comment]
Hello @ValentinoPeluso ,
Yes we have identified and fixed the issue internally. Will provide a patch as soon as its validated against our test suite.

**Comment by mdigiorgio** [comment]
Hi,
Could you guys try the patch I provided in #534 and tell me if it solves the problem?

Thanks.

**Comment by ValentinoPeluso** [comment]
I tried the suggested patch. The memory consumption reduced a little bit but is still almost the double the expected one.

**Comment by GeorgeARM** [comment]
@ValentinoPeluso can you provide us with your build command and the test that you are trying to run?

FYI the peak memory will be higher due to internal reshapings that we do to the weights tensors but you execution memory should be close to what you expect. You are noticing that on models with big conv or FC layer like alexnet but you shouldn't notice something similar t for models with smaller ones. You can optimize your peak memory at graph level when you prepare your graph for execution, something that we do not do at the moment as our graph API is for testing purposes, but the interfaces for doing that are in place.

**Comment by ValentinoPeluso** [comment]
I am not using the Graph API but the NEON runtime routines. In addition, I'm using the memory manager provided by ACL by calling the manage method before the configure of the first function using a tensor and the allocate after the configure of the last function using that tensor. 
I have already taken into account the memory requirements for tensor reshaping, that is im2col, weight reshaping, weight transposing and gemm output (I'm using only GEMM convolutions).
For building, I'm using
`scons Werror=1 debug=0 asserts=0 neon=1 opencl=0 examples=1 build=native`

while for measuring memory, I am using /usr/bin/time unix utility.

**Comment by mdigiorgio** [comment]
Are you sure `time` takes into account the memory usage of the GPU? Might be worth checking if it's only the RAM. In that case, what you see is correct.

**Comment by ValentinoPeluso** [comment]
@mdigiorgio I'am not using GPU. Only CPU (NEON).

**Comment by ValentinoPeluso** [comment]
https://github.com/ARM-software/ComputeLibrary/issues/541

**Comment by ValentinoPeluso** [comment]
Here I provide more details about my experiments.

Platform : linux Ubuntu-Mate 16.04 32bit
Version: Compute Library 18.08 with patch from issue #534
strings libarm_compute.so | grep arm_compute_version: 
arm_compute_version=v18.08
Build options: {'opencl': '0', 'neon': '1', 'examples': '1', 'asserts': 
'0', 'debug': '0', 'Werror': '1', 'build': 'native'} 
Git hash=52ba29e936b8e711e8acdfe819e36f884d4f3fe1

I have written a simple CNN with a cascade of 4 ConvLayers and Relu 
using the runtime abstraction.

The input img has dimensions (NCHW) 1x24x128x256. The convolutions are 
3x3 with stride 1 and padding 1 on both x and y dimension.

weight conv0 (CoutxCinxHxW) 96x24x3x3

weight conv1 (CoutxCinxHxW) 64x96x3x3

weight conv2 (CoutxCinxHxW) 32x64x3x3

weight conv3 (CoutxCinxHxW) 8x32x3x3

The convolutional layers used are NEGEMMConvolutionLayer. I have used 
the memory manager for both
managing the memory requirements of each layer and also the input/output 
memory.
The expected memory footprint of the running process is around 256 MB.
Instead measuring the memory with the linux command /usr/bin/time -f 
"mem=%M" I obtained 320 MB.

The most important problem is that adding layers of lower complexity, RAM usage increases a lot. This should not happen as the memory manager should allocate RAM resources according the most complex layer.

I attach the code to reproduce this experiment.

[neon_conv.txt](https://github.com/ARM-software/ComputeLibrary/files/2378889/neon_conv.txt)

**Comment by GeorgeARM** [comment]
Hello @ValentinoPeluso,

Can you check if your weights are actually used? GEMMConvolutionLayer usually reshapes weights internally, thus you might double allocate weights. You can call `prepare()` before running for the convolution layers, and then check if weights are used using the `is_used()' call. If they are no longer used you can free them as they reside transformed inside the function.

**Comment by ValentinoPeluso** [comment]
I tried with weights0.allocator()->free() and so on but I did not obtained any improvement. I do not think that this is the problem as weights require only around 0.4MB of memory. 

In addition, in my theoretical computation I have already counted weights twice.

There is still a difference of 75MB that could not be solved by freeing the memory of weights.

In order to further investigate the problem, I roughly analyze the evolution of memory occupation along the execution. I added some sleep(10) commands and check the memory with htop.

After the allocate() the memory grows from almost 0 to 175M. Then, it remains constant till the first run, as finalize() and acquire() do not add any contribution. After the first run, RAM increases of about 80M (total 255). After the second run, it increases again of 65M (total  320M)  and then remains constant until the end of execution.

Could you check if I used memory manager properly in the previous code? Thanks for your support.

**Comment by abhajaswal** [comment]
Is this BUg solved? Anny update on this?

**Comment by abhajaswal** [comment]
Kindly  reply , is this issue on going? I am using 19.05 version currently!!! And i use neon instead of CL,

**Comment by morgolock** [comment]
Hi @abhajaswal 

Apologies for the delay. This is something currently in our backlog and we will be looking into it after the next release 19.08.

**Comment by GeorgeARM** [comment]
@abhajaswal do see such behavior with 19.05? I am looking at the total memory and seems to be close for NEON and CL.

**Comment by morgolock** [comment]
We cannot reproduce the problem.

Please reopen if you still need support and we will investigate this further, for that we would need more details about the way you measure memory consumption in both cases.
