### ISSUE TITLE
only support grayscale input

### ISSUE THREAD

**Issue by ChenFengAndy** [ARM-software/ComputeLibrary#57]
Can it support input with RGB channels?

**Comment by yangyanzhan** [comment]
I have implemented a network in ACL for RGB format images. It works perfectly. I think they do have support for RGBs. Which API are you using that you think only supports grayscale format?

**Comment by ChenFengAndy** [comment]
Your answer partially addresses my concern. 
"Tensors are defined by a DataType plus a number of channels (Always expected to be 1 for now) and their dimensions are expressed as [width, height, feature_maps, batch]" 
So feature_maps should be the channel for input layer.
What's your feeling about its performance? faster than NNPACK?

**Comment by GeorgeARM** [comment]
Hello @ChenFengAndy,

Channels must be stored in a planar way for tensors used in CNN functions rather than interleaved. You can process tensors of an arbitrary number of dimensions as long as the data is stored in planes.
We haven't compared ACL with NNPACK yet.

Closing this issue as original question has been addressed.
