### ISSUE TITLE
ARMv8.2-DotProd instructions are used in arch=arm64-v8a

### ISSUE THREAD

**Issue by jty2a** [ARM-software/ComputeLibrary#606]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

arm_compute_version=v18.11 Build options: {'embed_kernels': '1', 'opencl': '0', 'pmu': '1', 'arch': 'arm64-v8a', 'standalone': '0', 'neon': '1', 'build_dir': 'linux-arm64-v8a-neon', 'debug': '0', 'validation_tests': '0', 'examples': '1', 'asserts': '0', 'mali': '1', 'benchmark_tests': '0', 'compiler_cache': 'ccache', 'os': 'linux', 'Werror': '1'} Git hash=b9abeae0897bef74553ba9800c4ff5f74131c5b4

**Platform:**

Linux aarch64

**Operating System:**

Ubuntu Linux bionic

**Problem description:**

On hardware that has the ARMv8.2-DotProd, SIMD Dot Product extension, armcl built with arch=arm64-v8a uses the SDOT/UDOT instructions.  This is contrary to the expectation that armcl needs to be built with arch=arm64-v8.2-a to use the instructions.

**Comment by jty2a** [comment]
The issue is that it isn't consistent with previous responses as to what is necessary to enable 8.2 features.  In #569, the response given is that "to enable fp16 you have to compile for arch=arm64-v8.2-a architecture".

**Comment by AnthonyARM** [comment]
Yes, because fp16 relies on the toolchain supporting the instructions for it, whereas for dot product there is no toolchain support needed: the assembly code uses a macro which directly output the op code for the instruction.
This was done because at the time the support for the dot product instruction wasn't present in the toolchains

**Comment by jty2a** [comment]
So now that there is DotProduct and fp16 toolchain support, and ACL decides on its own whether or not to use v8.2-a features regardless of the value of arch, why keep arch=arm64-v8.2-a as a valid target architecture parameter?

**Comment by AnthonyARM** [comment]
Because dot product support is a single instruction which is used in blocks of assembly whereas the fp16 code does rely on a whole range of instructions and makes use of the NEON intrinsics and therefore can't be done without toolchain support which is why fp16 only works for v8.2, and that's why we've got the v8.2 arch.
