### ISSUE TITLE
Clarify the relationship between OpenCL and NEON support

### ISSUE THREAD

**Issue by mablem8** [ARM-software/ComputeLibrary#630]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
* arm_compute_version=v18.11
* Build options:
  * embed_kernels: 0
  * install_dir: $HOME/sw/ComputeLibrary-aarch64/install
  * gles_compute: 0
  * arch: arm64-v8a
  * opencl: 1
  * neon: 1
  * build_dir: $HOME/sw/ComputeLibrary-aarch64/build
  * benchmark_tests: 1
  * validation_tests: 1
  * build: cross_compile
  * asserts: 0
  * debug: 0
  * openmp: 0
  * extra_cxx_flags: '-std=c++14 -fPIC -march=armv8-a+fp+simd -mtune=cortex-a53 -mcpu=cortex-a53+fp+simd'
  * os: linux
  * cppthreads: 1

**Platform:** Cross-compiling on x86_64 for Cortex-A53 

**Operating System:** Cross-compiling on Ubuntu 18.04 for PetaLinux

**Problem description:** Clarify the relationship between `scons` parameters `opencl` and `neon`. A note from over a year ago [here](https://community.arm.com/processors/b/blog/posts/running-alexnet-on-raspberry-pi-with-compute-library) states that NEON acceleration will not be used if OpenCL is not enabled. Is this still true? What happens if `opencl=0 neon=1`?

**Comment by mo-morikawa** [comment]
Now that there is another option `gles_compute`, I will be happy if it is included in an answer to this question. Thanks!

**Comment by gmiodice** [comment]
Hi @mo-morikawa,

many thank for reporting this documentation bug. Both NEON and OpenCL can be enabled at the same if your platform has OpenCL acceleration (for instance on Arm Mali-GPUs) and an Arm-based CPU with NEON acceleration.

I labelled this ticket with "Documentation bug"

Thanks,
Gian Marco

**Comment by GeorgeARM** [comment]
Hello @mo-morikawa,

Well there in no relationship between the scons options. Meaning that if you set `neon=1` you will include the NEON backend, if you set `neon=0` you will not. Same goes for `gles_compute` and `opencl`.

What confused you is that in order to compile our graph API you needed to compile for `opencl=1` always as they were build/link dependencies, from 18.11 and after this has been resolved and you have a pluggable backend interface for the graph. Now depending on what backends you build for a backend will be registered to the graph and enable support for that at graph level.

Hope this helps.

**Comment by mo-morikawa** [comment]
Thanks a lot!

**Comment by mpekatsoula** [comment]
Marking as resolved. Reopen if needed
