### ISSUE TITLE
Best way to pass a c++ vector as an argument to an OpenCL kernel in Compute Library.

### ISSUE THREAD

**Issue by ssj4gogeta** [ARM-software/ComputeLibrary#641]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:**
arm64-v8a

**Operating System:**
Android Pie

**Problem description:**
I am writing a custom opencl kernel and wanted to know what is the best way to pass a c++ vector as an argument to my OpenCL kernel in Compute Library.

Any leads will be appreciated.

Thank you.

**Comment by Wheest** [comment]
How necessary is it that this component integrates with Compute Library?

Since you just want to send an `std::vector` to a custom OpenCL kernel, could you just use that workflow.  Look into standard OpenCL C/C++ tutorials, such as [here](http://simpleopencl.blogspot.com/2013/06/tutorial-simple-start-with-opencl-and-c.html) and [here](https://cnugteren.github.io/tutorial/pages/page1.html).

Copying an `std::vector` to a `cl::Buffer` can be done like so:

```
std::vector<float> host_a = {5, 2, 1, 6,
                               3, 7, 4, 1};
auto device_a = cl::Buffer(context, CL_MEM_READ_WRITE, host_a.size()*sizeof(float));
```

You need to establish the `context` object in the ways described in tutorials, as well as loading the kernel and passing the `cl::Buffer device_a` to it.

Reply if you think you will need Compute Library in some way, otherwise I would recommend Stack Overflow with the OpenCL tag.

**Comment by ssj4gogeta** [comment]
Thanks.
