### ISSUE TITLE
Data type not supported NEON

### ISSUE THREAD

**Issue by GAnto85** [ARM-software/ComputeLibrary#647]
Hi all !! I'm running a convolutional layer with ARM compute library with neon enabled. The standard Datatype is F32 but i'm interested at using Fixed point 16bit. This message is what i get if i dare to change the DataType to DataType::F16. 

ERROR in configure src/core/NEON/kernels/NEIm2ColKernel.cpp:372: Data type not supported 
!!!!!!!!!!!!!!!!!!!!!!!!!!!

Could anybody help please?

**Comment by gmiodice** [comment]
Hi @GAnto85,

thanks for using ACL :)

since DataType::F16 is a floating point 16bit data type and not a fixed-point (integer) 16bit one, this requires a specific CPU Arm architecture to run it. In particular, you need arm64-v8.2-a in order to be able to run the functions with that data type. 

What platform are you using?

Thanks,
Gian Marco

**Comment by GAnto85** [comment]
hi , I am using a cortex A9 which is armv7a. But I am interested in fixed
point 16 convolution. Is it possible to use data in fixed 16?
Thanks!

**Comment by AnthonyARM** [comment]
F16 is floating point 16 (Which requires hardware support). 
We don't have fixed point 16 integer support however we have quantized asymmetric 8bit (QASYM8) which you can try.

**Comment by GAnto85** [comment]
Thank you very much , i will give it a try!

**Comment by morgolock** [comment]
Hi @GAnto85
As mentioned, armv7a has no support for FP16. You need at least arm64-v8.2-a to use FP16 with ACL.

I'll close this ticket, if you have problems with QASYMM8 please open a new issue.
