### ISSUE TITLE
How to install aarch64-linux-gnu and arm-linux-gnueabihf in cygwin for cross compilation

### ISSUE THREAD

**Issue by BhaskarsarmaP** [ARM-software/ComputeLibrary#661]
Need process of installing cross compiler in cygwin. I have installed scons and need the process of installing cross compiler for arm .

**Comment by morgolock** [comment]
Hi @BhaskarsarmaP 

Please take a look at the documentation on how to build ACL on Windows:
https://arm-software.github.io/ComputeLibrary/v19.02/index.xhtml#S3_5_windows_host

Hope this helps.

**Comment by BhaskarsarmaP** [comment]
Hi ,

I want to cross-compile compute library on windows machine using windows command prompt.

Are there any linaro cross compiler executables(arm-linux-gnueabihf-g++ && arm-linux-gnueabihf-g++) available in windows, which can be used to cross compile compute library without using windows subsystem/cygwin ?

**Comment by mpekatsoula** [comment]
Hi @BhaskarsarmaP 

You can check on the linaro [website](https://www.linaro.org/downloads/). There are binaries for mingw32, although we haven't tried this. The easiest and supported way is what @morgolock suggested.

**Comment by morgolock** [comment]
Hi @BhaskarsarmaP 

In theory it should  be possible to build ACL on Windows natively but in practice this is difficult because you need a linux/unix toolchain. 

When running windows there are two options for building ACL:

1. Cygwin
2. Ubuntu on Window

Please refer to the link I mentioned in my previous comment for more details.
