### ISSUE TITLE
For GPU, Run 10 images at the same time will be faster than running 10 times one by one ?

### ISSUE THREAD

**Issue by zhangruiopenailab** [ARM-software/ComputeLibrary#671]

**Comment by AnthonyARM** [comment]
Yes, it might be faster, especially if you have a big GPU because with a single image the jobs sent to the GPU might end up being too small and therefore not all the GPU cores will be used, whereas if you batch your images then more threads will be needed and therefore the GPU will be better utilised in theory.
In practice it really depends on your network, the size of the images, which GPU you have and how many cores.
