### ISSUE TITLE
Does CLconvolution support 128x4 kkernel

### ISSUE THREAD

**Issue by abhajaswal** [ARM-software/ComputeLibrary#683]
Arm compute library - 19.02

**Platform:** Arm

**Operating System:** linux

**Problem description:**

As per the deciption for convolution , 3x3 , 9x9, 5x5 kernel size is supported . does it support 
128x4 kernel size for convolution?

**Comment by abhajaswal** [comment]
Can i use GEMM convolution for 128x4 kernel size?

**Comment by abhajaswal** [comment]
Can i use GEMM convolution for 128x4 kernel size?

**Comment by abhajaswal** [comment]
Can i use GEMM convolution for 128x4 kernel size?

**Comment by morgolock** [comment]
Hi @abhajaswal 
I think you refer to https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEConvolution.h#L64 . In this case, the function does not use GEMM, it's just doing a 2D convolution and supports the kernel sizes listed in the documentation.

GEMM is used in the function NEConvolutionLayer, but GEMM does not know anything about kernel sizes, it's just a function implementing matrix multiplication  α * A * B +  β * C, where  A, B and C are matrices of the right sizes so that the matrix multiplication operation is well defined and α and β two scalars.

**Comment by GeorgeARM** [comment]
Hello @abhajaswal ,
You can use the `[CL|NE]ConvolutionLayer` functions, this will dispatch your convolution using the appropriate and more optimal implementation. In you 128x4 case it will use a GEMM-based convolution.
Hope this helps.

**Comment by abhajaswal** [comment]
Thanks for the information i have the trained model,  i will try to use the GEMM method using direct ACL graph method
