### ISSUE TITLE
Using signed types as conditions in Im2Col

### ISSUE THREAD

**Issue by macenpav** [ARM-software/ComputeLibrary#686]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v19.02 Build options: {'embed_kernels': '1', 'mali': '0', 'arch': 'arm64-v8a', 'opencl': '1', 'neon': '1', 'gles_compute': '0', 'debug': '1', 'validation_tests': '1', 'build': 'native', 'cppthreads': '1', 'benchmark_tests': '1', 'os': 'linux', 'Werror': '1', 'examples': '1'} Git hash=27a2694f50199324bae521f32fd6bc31dd1a2a5c
**Platform:**
Vivante OpenCL
**Operating System:**
Yocto Linux

**Problem description:**
In Im2Col.cl (and other kernels) there the following lines of code:
https://github.com/ARM-software/ComputeLibrary/blob/29f6788cee8881c5523a042a0ac9b0131d993768/src/core/CL/cl_kernels/im2col.cl#L323

https://github.com/ARM-software/ComputeLibrary/blob/29f6788cee8881c5523a042a0ac9b0131d993768/src/core/CL/cl_kernels/im2col.cl#L329

E.g. for quantized models, `cond0` is char3. The issue that I am running into is that the same kernel produces different results on different platforms (Intel/Vivante OpenCL - Intel producing the expected result). In the code you are storing the result of a relational operation in cond0 (char3) which is a signed type. OpenCL [select](https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/select.html) only compares the MSB and not if the value is zero/non-zero, so the result would be platform dependent and thus being evaluated differently. Is my assumption correct or am I talking non-sense? Thanks.

**Comment by morgolock** [comment]
Hi @macenpav 

I've checked the CL spec and states that the relational ops return -1 if cond is true and 0 otherwise. The code you've shared should behave according to the spec and is platform independent. (OpenCL 2.0 Spec, section 6.3.4. Relational Operators)

![relational](https://user-images.githubusercontent.com/5577511/58476549-f506c200-8148-11e9-9b17-3e2229a80157.png)

**Comment by macenpav** [comment]
Hi @morgolock 
cannot -1  for a signed type be represented differently than "all bits set" based on the platform? For unsigned yep - you underflow from 0000 0000 to 1111 1111. For a signed type you can represent -1 in multiple ways (1111 1111, 0111 1111, 1111 1110). Which would lead to MSB not necessarily being set to 1.

**Comment by morgolock** [comment]
Hi @macenpav 

The results of the relational operators on vectors are likely to be fed into the select operation. I think the -1 in the spec is just an example and what's likely to happen in reality is that all bits are set to 1 regardless the multiple representations of -1 on different systems. 

Otherwise, you're right, it wont work well. Select() would be incorrect and the relational operators would be incompatible with select (which would be very odd!). 

We have tested Im2Col thoroughly on ARM GPUs and have not found any problems with this.

**Comment by macenpav** [comment]
Hi @morgolock 
Well that depends on the platform-specific OpenCL implementation, which seems to be the case I am running into :). Thanks for the answers though.
