### ISSUE TITLE
Unexpected CLGEMM (F16) performance comparison results between Mali-G71 (bifrost arch) vs Mali-T880 (midgrad arch)

### ISSUE THREAD

**Issue by atrah22** [ARM-software/ComputeLibrary#70]
Hello,
1) Are the OpenCL functions optimized for Mali bifrost architecture (Mali-G71)? Or are they mainly optimized for Mali Midgrad architecture? or for both architectures?
2) I ran CLGEMM on Huawei Mate 9 (ARM Mali-G71) and Galaxy S7 edge (Mali-T880) [both have same number of shader cores].  I used the same code as shown in "https://github.com/ARM-software/ComputeLibrary/issues/62".  Summary of the result is quite unexpected for Mali-G71. I stated the summary below:
a) For larger matrix size, the performance of Mali-T880 is significantly better (~2x to 3x) than  Mali-G71
b) As the matrix size increases, the throughput "GOPS/s" increases in case of Mali-T880 but it decreases in case of Mali-G71!

Th results are stated below:

Matrix size= (M*N*K)

Matrix size= 196 * 160 * 528	       
        [Mali-T880] --> **12.34** GOPS/s,  [Mali-G71] --> **12.77** GOPS/s
Matrix size= 196 * 256 * 1152	       
        [Mali-T880] --> **25.08** GOPS/s,  [Mali-G71] --> **31.38** GOPS/s
Matrix size= 12544 * 64 * 147	
        [Mali-T880] --> **41.32** GOPS/s,  [Mali-G71] --> **51.59** GOPS/s
Matrix size= 3136 * 192 * 576
        [Mali-T880] --> **71.83** GOPS/s,  [Mali-G71] --> **41.17** GOPS/s
Matrix size= 1000 * 1000 * 1000 
        [Mali-T880] --> **75.23** GOPS/s,  [Mali-G71] --> **20.60** GOPS/s

3) It would be of great help if anyone could give a reason for such performance gap for larger matrix size. Is it an optimization issue (not optimized for bifrost arch) or an architecture issue?

**Comment by gmiodice** [comment]
Hi @atrah22,

At the current stage, CLGEMM (both fp32 and fp16) have not been optimized for Mali Bifrost architectures but just for Mali Midgard.

The reason why you see better performance for large matrices should be behind the number of dispatched threads on the GPU. 

Let's take in consideration the 2 cases:
Matrix size= 196 * 160 * 528
and
Matrix size= 1000 * 1000 * 1000
Since each work-item (thread) computes 8x4 output elements for GEMM fp16, this means that we are going to dispatch:

196 * 160 * 528 - > ~1000 threads
1000 * 1000 * 1000 - > 31250 threads

In cases of few threads the risk is to dispatch the whole workload on few GPU cores and then to have less performance.

Hope this can help you.

Thanks,
Gian Marco
