### ISSUE TITLE
Precision Issue caused by float computing

### ISSUE THREAD

**Issue by blueardour** [ARM-software/ComputeLibrary#700]
Hi, 
I'm comparing the result of the CPU version and GPU version and found some kind of mismatch.
For example, CPU version give -0.747096, while GPU version gave -0.747196. The mismatch seems just the float computing issue, caused by different computing order.  As we know different order of float accumulation output different result (a +b +c != a + (b+c)).

I employ the following code to compare the result. 

`
static bool AlmostEqualAbsoluateRelative(float A, float B, bool verbose=false, float absolute=1e-4, float relative=FLT_EPSILON)
{
  float diff, largest;
  diff = fabs(A - B);
  if(diff <= absolute) return true;
  A = fabs(A);
  B = fabs(B);
  largest = (B > A) ? B : A;
  if (diff <= largest * relative) return true;

  if(verbose)
    printf("A(%f) B(%f) largest(%f), diff(%f)\n", A, B, largest, diff);
  return false;
}
`
However, even for absolute = 1e-4, there would still be some change to be different for the two version. I wonder if there are any guarantee for computing precision.

**Comment by morgolock** [comment]
Hi

From your description I understand that you run the neon and opencl functions but the outputs do not match because there is a small error. Am I right?
What function or kernel are you running?

Have you taken a look at ACL's validation tests for that specific function? This will give you an idea of the magnitude of the error expected in each backend.

**Comment by blueardour** [comment]
Hi, @morgolock 
Yes. That's right.

I'm debugng on NEConvolutionLayer and CLConvolutionLayer. After calling get_convolution_method, they all indicated the Winograd method was used. I also tried to specific the conv method by calling XXDirectConvolutionLayer/XXGEMMConvolutionLayer/XXWinogradConvolutionLayer (XX means CL or NE).

**Comment by morgolock** [comment]
Hi @blueardour 

Winograd layer's results from the neon backend won't match exactly the ones in the opencl function because the order of the floating point operations is not be the same (as you described earlier)

For winograd you can check out the tolerance we use to validate the results in:
https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/NEON/ConvolutionLayer.cpp#L53
https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/CL/Winograd.cpp#L57

An absolute tolerance of 1e-4 is not good as it's too small.

Hope this helps.

**Comment by blueardour** [comment]
HI  @morgolock  Thank you for the explaination and the link provided.
