### ISSUE TITLE
Neon functions are only using single core,not using multiple core

### ISSUE THREAD

**Issue by waveajay** [ARM-software/ComputeLibrary#707]
Is neon function use only single core?
How to make use of multi core processor

**Comment by morgolock** [comment]
Hi @waveajay 

It depends on the way you compile the library and how you run your example or tests. ACL implements two schedulers: C++11 (cppthreads=1) and OpenMP (openmp=1). If you compile with cppthreads=0 and openmp=0 then you get a scheduler that runs all the workloads in a single thread.

Most of the tests and examples accept an argument --threads=number which lets you overload the number of threads, the scheduler otherwise would have detected how many cores are in the cpu and try schedule one kernel per core.

Neon functions will attempt to run one kernel per CPU core, that is if the kernel supports multithreading: https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/core/IKernel.h#L49 . Most kernels do support multiple threads.

You can also take a look at the C++ scheduler https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/CPP/CPPScheduler.cpp#L288

You can check how many threads the scheduler is trying to use with this code:
`std::cout << "Number of threads " <<  Scheduler::get().num_threads_hint()  << std::endl`
