### ISSUE TITLE
convert from format 420  to 422 (2 planes)

### ISSUE THREAD

**Issue by joel-mi** [ARM-software/ComputeLibrary#71]
I'm trying to configure NEColorConvert for performing conversion from format 420  to 422 (2 planes -  Y plane, followed by the UV plane (YYYYYYY UVUVUVUV)
I guess that I should use IMultiImage for this purpose, but I'm having some difficulties understanding how to configure it - for example : how to specify the number of planes
Can you help with that ? Maybe you have some sample code showing such IMultiImage configuration ?

**Comment by mpflanzer** [comment]
The library currently only supports YUV 4:2:0 but not 4:2:2.

But depending on how you want to use converted image you might not need color convert and IMultiImage. The only difference between 420 and 422 is that the former is also horizontally sub-sampled for UV. So to get 422 you would only need to repeat every row of the UV plane twice. Instead of a multi-image you could use two tensors to represent the Y and the UV plane.

The number of planes is directly derived from the specified image format.

**Comment by GeorgeARM** [comment]
Closing issue.
Compute Library does not support YUV 4:2:2 format and the above suggestion can workaround this problem.
Reopen issue in case your problem has not been resolved or if you want this to become a feature request for adding this format in the library.
