### ISSUE TITLE
Mismatching output in FC layer for batch size more than one

### ISSUE THREAD

**Issue by nhkrishna** [ARM-software/ComputeLibrary#711]
Hi ACL Team,

I'm trying to create a FC layer for batch size greater than one. But i encountered with incorrect results.
Below are input/output dimensions of the FC layer.
Input dimensions: 1x1x100x200(WxHxCxBS)
Output dimensions: 1x1x5x200(WxHxCxBS)

I have [attached](https://drive.google.com/open?id=13m1XHAEZ7uH9HDlfjceeTqMZudO62-gD) the standalone FC layer implementation to reproduce the issue from your side.

Above implementation works fine for Batch size=1  if i create the 1D outputTensor instead of the 2D Tensor in the implementation. Does configuring the BATCH_SIZE parameter of outputTensor is valid in the implementation?

Any help would be highly appreciated.

Thanks,
Hari

**Comment by morgolock** [comment]
Hi @nhkrishna 

Please take a look at the line 179 in your FcLayer.cpp:

`memcpy((float*)inputTensor.buffer(), input_data, sizeof(float)*input_size*BATCH_SIZE);`

This is likely to be the source of the problem because ACL's tensors might have some padding and the copy operation won't work properly. The copy operation writes a contiguous chunk of memory, but in ACL's tensors you have padding between columns and this padding should be skipped by the copy operation.

When moving data in/out of ACL's tensors you should use `execute_window_loop` as described in the documentation: https://arm-software.github.io/ComputeLibrary/v19.05/architecture.xhtml#S4_6_4_working_with_objects

You could as well take a look at our validation test for FC layer:
https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/NEON/FullyConnectedLayer.cpp

As you see here we have tests to validate when batch size is > 1
https://github.com/ARM-software/ComputeLibrary/blob/master/tests/datasets/FullyConnectedLayerDataset.h#L154

You could modify our dataset to test the particular shape from your example.

Hope this helps.

**Comment by nhkrishna** [comment]
Thanks for your response @morgolock .

I have reimplemented the fc layer by introducing `execute_window_loop` to copy data to tensor and vice versa. Looks like the problem is around copying data to the padded tensors(ACL FClayer works fine with our test dimensions).  In my implementation i have observed that weight data is incorrectly copied to padded weight tensor. 
Could you please look into this [attached](https://drive.google.com/open?id=13YTHMgmkwGTnrZGMiR3O-BpIlTNnydvC) setup to reproduce the issue and suggest better approach to use  `execute_window_loop`  or any tensor dimensions configuring is missing in the implementation. 

Thanks,
Hari

**Comment by nhkrishna** [comment]
Hi @morgolock ,

It looks like wrong tensor offset calculation(..`offset(int n, int c, int h, int w)`..) leads to the wrong results in my implementation. If i modify the offset calculation then i'm able to get the correct results. 
And also i have used another approach instead of calculating the offset. I just used post incremented count variable for the input_data in the lambda function. This also giving the correct results. It seems second approach is more optimal than offset calculation. So I'm using the second approach in my implementation.

**Comment by nhkrishna** [comment]
Hi @morgolock ,

I have one another question. Does all the ACL kernals(softmax, pooling, convolution..etc) supports the batch size?

**Comment by morgolock** [comment]
Hi @nhkrishna 

In general yes unless otherwise stated in the header file comments for the particular function you are trying to use. If in doubt please take a look at the function's header file, that should clarify.

**Comment by nhkrishna** [comment]
Thanks for your response @morgolock.
