### ISSUE TITLE
Column major or Row major

### ISSUE THREAD

**Issue by shubh809** [ARM-software/ComputeLibrary#727]
**Problem description:**
I have a doubt do arm_cl APIs expect a row major data or column major stored data?

**Comment by morgolock** [comment]
Hi @shubh809 

Row major, be aware that there is padding between rows in the tensors due to some functions requirements.
Please take a look at the documentation to learn more about this and how to move data to and from ACL's tensors.
https://arm-software.github.io/ComputeLibrary/v19.05/architecture.xhtml#S4_6_4_working_with_objects

**Comment by RuABraun** [comment]
@morgolock 

This does not seem accurate? Probably I've misunderstood something but in the example you show the first dimension is iterated over first, relevant lines are:
```
const TensorShape shape(width, height, batch);
[...]
// for( unsigned int z = 0; z < batch; ++z)
// {
//   for( unsigned int y = 0; y < height; ++y)
//   {
//     for( unsigned int x = 0; x < width; ++x)
//     {
//       *reinterpret_cast<float*>( input.buffer() + input.info()->offset_element_in_bytes(Coordinates(x,y,z))) = src_data[ z * (width*height) + y * width + x];
//     }
//   }
// }
```
