### ISSUE TITLE
Incorrect results for ConvLayer in NHWC DataLayout

### ISSUE THREAD

**Issue by pranathibl** [ARM-software/ComputeLibrary#733]
Hi,

I am trying to do convolution on NHWC data. I am seeing incorrect results. whereas it is giving correct results in NCHW DataLayout.

Below is the code attached.
[convLayer_NHWC_dataLayout.zip](https://github.com/ARM-software/ComputeLibrary/files/3447449/convLayer_NHWC_dataLayout.zip)

Please let me know if i am doing anything wrong.

Thanks,
Pranathi.

**Comment by pranathibl** [comment]
any update on this?

**Comment by morgolock** [comment]
Hi @pranathibl 

I've just run your test and while the two outputs do not match exactly they are very close with a small error probably due to the fact that the order of the floating point operations produces different results.

The error is smaller than the tolerance we use in our validation tests:
`constexpr AbsoluteTolerance<float>  absolute_tolerance_float(0.0001f);`
https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/CL/ConvolutionLayer.cpp#L48

![nhwc-nchw](https://user-images.githubusercontent.com/5577511/63530057-a5dced00-c4fd-11e9-9185-45281613807b.png)

Hope this helps.

**Comment by pranathibl** [comment]
Previously I have used v19.02. I tried it with 19.05, outputs are matching.

Thanks.
