### ISSUE TITLE
QASYMM8 Convolution is consuming more time than F32 in ACL 19.05 on raspi

### ISSUE THREAD

**Issue by uu-praveeng** [ARM-software/ComputeLibrary#746]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v19.05 Build options: {'arch': 'armv7a', 'opencl': '0', 'neon': '1', 'build': 'cross_compile', 'debug': '0', 'os': 'linux', 'Werror': '1'}

**Platform:**
raspberrypi -3b
**Operating System:**
raspbian stretch

**Problem description:**
QASYMM8 convolution is consuming more time that F32 convolution.
Below are convolution dimensions and parameters. 

input dimensions - 227x227x3
weights - 3x3x3x64
bias - 64

Benchmarking numbers using F32 is arounf **127 ms** and using QASYMM8 it is **135ms**

Is this expected? Do you have any plans to work on this performance improvement?

Thank you.

**Comment by morgolock** [comment]
Hi @uu-praveeng 

The armv7a target is not as optimised as  arm64-v8a or later. There are no plans to optimise armv7a code further at present.

On arm64-v8a, 4xA53, we see qasymm8 is slightly faster than FP32.

**Comment by uu-praveeng** [comment]
Hi @morgolock 
Output of 'strings libarm_compute.so | grep arm_compute_version':
arm_compute_version=v19.05 Build options: {'arch': 'arm64-v8a', 'opencl': '0', 'neon': '1', 'build': 'cross_compile', 'debug': '0', 'os': 'linux'}

Platform:
HiKey-960

Operating System:
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial


I tried to verify the same convolution setup on the HiKey-960(armv8a based) board and I did not see any performance improvement from FP32(**14ms**) to INT8(**26ms**).In general this is not unexpected. 
Could you let me know the target platform that you have used to compare the bench marking from FP32 to INT8. Ideally we were expecting a 4X improvement from FP32 to INT8.  

Thank you.

**Comment by uu-praveeng** [comment]
any update on this?

**Comment by morgolock** [comment]
Hi @uu-praveeng 
We see small improvements in performance, the main benefits however from uint8 are:
(https://developer.android.com/ndk/guides/neuralnetworks#quantized_tensors)

- Your application is smaller, as the trained weights take a quarter of the size of 32-bit tensors.
- Computations can often be executed faster. This is due to the smaller amount of data that needs to be fetched from memory and the efficiency of processors such as DSPs in doing integer math.


On the mate9 the results for mobilenet v1 for the 19.05 release:
FP32: 75.3ms vs QASYMM8: 62.9ms

Hope this helps.

**Comment by uu-praveeng** [comment]
Hi @morgolock,

Thanks for the update. 
I totally agree with memory reduction part using QASYMM8 . But on performance front I still have some doubts. 

I benchmarked  mobilenetv1 and mobilenetv2 graph examples  in 1905 for FP32 and QASYMM8. We cannot compare FP32 vs QASYMM8 of mobilenetv1 . Reason being, batch normalization and activation are fused in QASYMM8 Convolution which are not done in FP32 network. 

No of mobilenetv1 layers in F32 are 57 where as in QASYMM8 they are only 30 layers. 
Let me know if my observations are correct? If yes, there might be still some scope for performance improvement. 

Thank you,
Praveen.

**Comment by uu-praveeng** [comment]
Any update on this

**Comment by morgolock** [comment]
Hi @uu-praveeng 

What you see in your test is expected. On armv8a / armv7a, the convolution layer for qasymm8 is expected to be slightly slower than the convolution layer for fp32.

On armv8.2-a we see a speedup of about 1.5x for qasymm8 due to the use of the dot product instruction.

Hope this helps.

**Comment by uu-praveeng** [comment]
Hi @morgolock ,

For the same convolution that I have mentioned above there is a usage of memory is reduced from 45396KMB to 31552KB from float to fix.

Is this expected .Ideally it should have beed 4x reduction in memory since the data-format is reduced from 32bit to 8bit now.

Hardware that I have used is Raspberrypi 3b.

Thank you,
Praveen.

**Comment by GeorgeARM** [comment]
Hello @uu-praveeng,

I suppose the Raspberry pi runs on 32bit, thus as @morgolock mentioned we don't have optimized paths for armv7a, meaning that the size of auxiliary memory required to perform the internal calculation can be bigger than armv8a. This is due to the increased number of kernels than we need to dispatch to execute the quantized convolution.

In terms of performance, in int8 convolution the accumulations take place in int32_t accumulators thus you shouldn't see a big performance improvement unless you have dot product acceleration which is present in armv8.2. 

Hope this helps.
