### ISSUE TITLE
Can I use CV_32F's opencv data type in Neon functions?

### ISSUE THREAD

**Issue by zanazakaryaie** [ARM-software/ComputeLibrary#766]
Hi.
I'm going to implement an algorithm with ACL which is already provided in OpenCV. The algorithm converts the RGB image to gray and then normalizes it to 0-1 with CV_32F data type to apply other steps which are mainly separable convolutions. 
I read the ACL documentation of Neon functions. Most of them just support 8U data type. Isn't there any solution to use ACL for accelerating CV_32F convolutions?

**Comment by morgolock** [comment]
Hi @zanazakaryaie 

What algorithm are you working on?

The CL/NEConvolution functions take the input as U8 and the kernel's coefficients as S16, as shown in the header file:
https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEConvolution.h

Instead of normilizing in [0,1] you could do it in [0,255] and then apply the convolutions.
Hope this helps.
