### ISSUE TITLE
Several questions about how to use the library

### ISSUE THREAD

**Issue by RuABraun** [ARM-software/ComputeLibrary#770]
1. AFAIK only arm64-v8a phones are guaranteed to have NEON. Does this mean one cannot reliably use this library for armv7a phones? Or does some logic underneath the function calls exist to make sure it won't crash for phones without NEON?

2. If some logic like that does not exist, what do you recommend using for SGEMM on armv7a phones?

**MOST IMPORTANT:** 3. How can I initialize a tensor from an existing float array? Or in other words wrap an existing array, whose memory I manage, with a Tensor so that I can pass it to the SGEMM functions this library provides.

**Comment by morgolock** [comment]
Hi @RuABraun 

1. Neon support is a requirement in ACL and the library does not check whether there is support for Neon or not. All functions in ACL require simd and there is no C++ fallback if this is not the case, so in the absence of neon support the library cannot do any work on the cpu side. 
But I think you could implement the logic to check for neon support in your app and only call into ACL if that is supported. Otherwise show an error or fallback to your own C++ implementation of the functions.

2. Cannot run ACL on CPU not supporting Neon.

3. There are two alternatives: a)copy the values into an ACL tensor or b)import the memory. Please take a look at the documentation on how to do these things: 
https://arm-software.github.io/ComputeLibrary/v19.08/architecture.xhtml#S4_6_4_working_with_objects
https://arm-software.github.io/ComputeLibrary/v19.08/architecture.xhtml#S4_8_import_memory

Please be aware that most ACL functions have padding requirements which means that between rows of the tensor there might be padding values, when moving data to/from tensors you should use execute_window_loop() as explained in the documentation.

Hope this helps.

**Comment by RuABraun** [comment]
Thank you for informative response!

I'm not working with images and will just use SGEMM so padding shouldn't be an issue I think.

I don't understand why `execute_window_loop()` is relevant for me though? Whenever I write to or read from the tensors I will be accessing it through the pointer. I'm just creating the tensor so I can pass in the right data structures to `NEGEMM::configure(...)` etc.

**Comment by morgolock** [comment]
Hi @RuABraun 

In general, functions require padding for its operands because they are implemented using vector instructions which read multiple elements per operation. To ensure the read/write operations performed by the kernels do not corrupt or access invalid memory regions the padding is added to the tensors when you call allocate(). When padding is added you cannot just assume the tensor data can be addressed contiguously because there are extra padding elements at the left,right, top and bottom of the tensors. So to iterate over the contents of a padded tensor we use `execute_window_loop()`

If you would like to use the `import_memory` feature, please see below the code showing how to do it. You should allocate the memory after calling configure() and use total_size() method to retrieve the buffer size.

```
    weights0.allocator()->init(TensorInfo(weights_shape_conv0, 1, DataType::F32));
    biases0.allocator()->init(TensorInfo(biases_shape_conv0, 1, DataType::F32));
    out_conv0.allocator()->init(TensorInfo(out_shape_conv0, 1, DataType::F32));

    conv0.configure(&src, &weights0, &biases0, &out_conv0, PadStrideInfo(STRIDE_WIDTH,STRIDE_HEIGHT,PAD_WIDTH,PAD_HEIGHT,DimensionRoundingType::FLOOR));

    weights0.allocator()->allocate();
    biases0.allocator()->allocate();

    char *inputMemBuffer = new char[src.info()->total_size()] ;
    src.allocator()->import_memory(inputMemBuffer);
    char *outputMemBuffer = new char[out_conv0.info()->total_size()];
    out_conv0.allocator()->import_memory(outputMemBuffer);
```

Hope this helps.

**Comment by RuABraun** [comment]
Disappointing to hear about the padding (as that means there's 10x more work for me than expected), but thank you for explaining.

One thing I'm confused about is [in the example](https://arm-software.github.io/ComputeLibrary/v19.08/architecture.xhtml#S4_6_4_working_with_objects) for using `execute_window_loop()`, the Tensor shape seems to be defined in reverse order to how the data is actually laid out? So if the tensor shape is `(X, Y,)`, then if I were iterating over a pointer one would do so like: `y * X + x`
(with `y` and `x` the changing iterators), instead of the usual: `x * Y + y`

Is that correct or is the example mistaken?

**Comment by RuABraun** [comment]
Also, how is one supposed to add biases when the output has multiple rows? Obviously for one row one can use the SGEMM function as the output and C (the bias) have the same shape, but when the input has multiple rows (which means the output will as well), the bias does not fit anymore. I could do it manually of course but am wondering whether a function for that already exists.

**Comment by morgolock** [comment]
Hi @RuABraun 

> One thing I'm confused about is [in the example](https://arm-software.github.io/ComputeLibrary/v19.08/architecture.xhtml#S4_6_4_working_with_objects) for using `execute_window_loop()`, the Tensor shape seems to be defined in reverse order to how the data is actually laid out? So if the tensor shape is `(X, Y,)`, then if I were iterating over a pointer one would do so like: `y * X + x`
> (with `y` and `x` the changing iterators), instead of the usual: `x * Y + y`.


If tensor shape is (width,height, ...) and layout is NCHW (the fastest changing dimension is the smallest one = width), then you would do `ptr[ ... + id.y() * width + id.x() ]`


Take a closer look at the code below filling an ACL tensor one element at time:
```
        // Fill the input tensor:
        // Simplest way: create an iterator to iterate through each element of the input tensor:
        Window input_window;
        input_window.use_tensor_dimensions(input.info()->tensor_shape());
        // Create an iterator:
        Iterator input_it(&input, input_window);
        execute_window_loop(input_window, [&](const Coordinates & id)
        {
            std::cout << "Setting item [" << id.x() << "," << id.y() << "," << id.z() << "]\n";
            *reinterpret_cast<float *>(input_it.ptr()) = src_data[id.z() * (width * height) + id.y() * width + id.x()];
        },
        input_it);
```

And the code below shows how to move the data from an ACL tensor into the buffer `dst_data`
```
        dst_data = new float[width * height * batch];
        Window output_window;
        output_window.use_tensor_dimensions(output.info()->tensor_shape(), Window::DimY); // Iterate through the rows (not each element)
        Iterator output_it(&output, output_window);
        execute_window_loop(output_window, [&](const Coordinates & id)
        {
            // Copy one whole row
            memcpy(dst_data + id.z() * (width * height) + id.y() * width, output_it.ptr(), width * sizeof(float));
        },
        output_it);
```
> In other words it seems to be column major (neighboring elements of the first dimension `width` are contiguous)?

Elements for the first dimension are always contiguous (except for the padding values mentioned in my previous post). But the first dimension could be either X axis (with) or Z (channels) depending on whether the datalayout is NCHW or NHWC.

Hope this helps.

**Comment by morgolock** [comment]
> Also, how is one supposed to add biases when the output has multiple rows? Obviously for one row one can use the SGEMM function as the output and C (the bias) have the same shape, but when the input has multiple rows (which means the output will as well), the bias does not fit anymore. I could do it manually of course but am wondering whether a function for that already exists.

Please take a look at `NEArithmeticAdditon` function in https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEArithmeticAddition.h

**Comment by RuABraun** [comment]
Thank you , this is what was confusing me:

> If tensor shape is (width,height, ...) and layout is NCHW

I'm used to the shape and layout always being the same! Since the shape started with `width`, I thought the layout would as well. Thank you for explaining.

> Please take a look at NEArithmeticAdditon function

Thank you.

**Comment by RuABraun** [comment]
One last question @morgolock

I noticed in one case (of a GEMM operation) that after calling `configure()` the input and output matrices (both 2D) have padding of 3 and 15. The end result is that `total_size` for both is 4 times bigger than normal. That seems very strange to me, I thought padding was only done between rows? It's like it's padding each element? Is this behaviour normal or must I have done something wrong?
