### ISSUE TITLE
Question for GEMM implementation in Winograd Convolution

### ISSUE THREAD

**Issue by wenfahu** [ARM-software/ComputeLibrary#804]
Hi, I am trying to understand the Winograd Convolution implementation in ACL. As explaind in the paper [Efficient Winograd or Cook-Toom Convolution Kernel Implementation on Widely Used Mobile CPUs](https://arxiv.org/pdf/1903.01521.pdf), the Hadamard product in Winograd domain is actually computed using GEMM. I have no idea how this is implemented in ACL. Any hints please? Many thanks!

**Comment by morgolock** [comment]
Hi @wenfahu 

A good place to start learning more about Winograd in ACL is the source code, please take a look at this file: https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/NEON/functions/NEWinogradConvolutionLayer.cpp#L554


A general idea behind the implementation of the Winograd Convolution Layer: Transform input to Winograd domain -> Run multiple GEMMs to compute the convolution in the Winograd domain -> Transform the results back to the output domain.

Hope this helps.

**Comment by wenfahu** [comment]
Thanks for your reply and it is of great help. And I found that the NEWinogradConvolutionLayer actually calls the following kernels:
+ NEWinogradLayerTransformWeightsKernel (executed only once in the first call to the run() method )
+ NEWinogradLayerTransformInputKernel
+ NEWinogradLayerTransformOutputKernel
+ NEGEMMAssemblyDispatch
+ CPPPermute (three times: weights, input and output)

The transformed input and weight tiles generally need to be reorganized to perform GEMMs. As the [source code](https://github.com/ARM-software/ComputeLibrary/blob/7f09cf7dfba61aad6d6d588b1b096f56bafaad5e/src/runtime/NEON/functions/NEWinogradConvolutionLayer.cpp#L570) shows, the `_gemm_function.run()` call runs 16 GEMMs in multiple threads. I suppose for Winograd Convolution F(2, 3) there should be 4 transformed  input tiles and 4 transformed  weight tiles involved in this call.  The overall process should be most likely the same as the process in the following image.
![image](https://user-images.githubusercontent.com/5833445/75232463-3f10f700-57f2-11ea-8d2d-f4e792641aca.png)

Am I right? Moreover, I am eager to know  the ACL implementation of reorganizing tiles and specific GEMM calls after the Winograd transforms. Please help. Many thanks.

P.S. I have spent lots of time trying to figure out what's behind `_gemm_fucntion.run()` and it ends up without a clue.

**Comment by gmiodice** [comment]
Hi @wenfahu ,

and thanks a lot for your interest on ACL! :)

First of all, I would like to share a presentation that I delivered a couple of years ago on this topic.

https://www.edge-ai-vision.com/2018/06/even-faster-cnns-exploring-the-new-class-of-winograd-algorithms-a-presentation-from-arm/

The presentation should give you an overview of how Winograd is implemented in ACL. The important things to remember are:
1) In order to use GEMM, we need to transform the input (activation), weights and output 
2) The number of GEMMs to run in parallel depends on the size of the output tile and is equal to the number of input values needed to compute the tile. To give you an example, to compute a 2x2 tile for 3x3 kernels, we need exactly 4x4 values so the number of GEMMs to run in parallel is 16. To compute a tile of 4x4 for 3x3 kernels, we need 6x6 input values so 36 GEMMs in parallel

Hope this can help ;)
Gian Marco

**Comment by wenfahu** [comment]
Hi @gmiodice ,
Thanks for your response and it is of great help! The presentation is really a marvelous explanation on Winograd convolution implementation. 

However, there are some questions which confuses me.
1. As is shown in the presentation ,  after the transform of a 4x4 input tile, the 16 elements of the transformed matrix is scattered into 16 channels of the transformed results, which is, the 16 elements of the same input tile is consecutive in the channel dimension. However, the implementation of input transform in ACL (https://github.com/ARM-software/ComputeLibrary/blob/36ccc90158c65844b3c53c5462c6d7d852b97278/src/core/NEON/kernels/convolution/winograd/winograd_transforms/input_4x4_fp32_fp32_integers.cpp#L136), which I understand, stores the consecutive channel elements of the transformed tile in the last dim(channel dimension). 
2.  Since the winograd convolution is performed  over the transformed input tiles and weight tiles. Considering the multi-dimension cases, where input tiles get multiple channels and the filter kernel tiles  also get multiple input channels and output channels, and the registers for matrix computation is always limited, how weight tile reuse over all input regions and  input region reuse over all output channels is achieved?

Thanks!

**Comment by mundya** [comment]
Hi @wenfahu,

I was one of the authors of the above paper, I hope I can help!

Your understanding of the NEON code is correct. We perform the Winograd transforms on four channels simultaneously. After the input transform we have NxN vector registers, each of which contains four channels of data. We scatter these into the NxN GEMMs and use `vst1_q` to write out the channels consecutively. (Since the GEMMs are [MxK] x [KxN] where K is the number of channels in the input tensor, and N is the number of channels in the output tensor).

Regarding point 2, I'm not entirely sure I understand your question - but if I do understand correctly, then we get reuse through the GEMM algorithm. E.g., each row of an A matrix (corresponding to the transformed inputs) is used to compute multiple columns of a C matrix, and each column of a B matrix (corresponding to the transformed filters/weights) is used to compute multiple rows of a C matrix. (See http://dl.acm.org/authorize?N91172 for more on how GEMMs achieve effective reuse).

The below picture _might_ help a little too:

![Winograd layout](https://user-images.githubusercontent.com/3439837/77524024-93a1a380-6e7e-11ea-9c18-627e6113b822.png)

**Comment by wenfahu** [comment]
Thanks, @mundya .  That is of great help and solves my confusion.
