### ISSUE TITLE
FullyConnected Layer QASYMM8_SIGNED data processing time is more than FP32

### ISSUE THREAD

**Issue by pateldarsh** [ARM-software/ComputeLibrary#816]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

arm_compute_version=v20.02.1 Build options: {'embed_kernels': '1', 'os': 'android', 'neon': '1', 'validation_tests': '0', 'benchmark_tests': '0', 'extra_cxx_flags': '-fPIC', 'arch': 'arm64-v8a'} Git hash=unknown

**Platform:**
IMX8X
**Operating System:**
Android

**Problem description:**

FullyConnected layer is taking more time for processing QASYMM8_SIGNED data type than FP32. I have attached code used for profiling. We quantized ONet ( Part of MTCNN https://github.com/timesler/facenet-pytorch ). The timing is increased due to Fully Connected layer ( NEFullyConnectedLayer ) and Matrix Multiplication ( NEPixelWiseMultiplication ). 

So I profiled it standalone using attached code ( renamed file as .txt ).

**Compilation Command** : _aarch64-linux-android-clang++ FCLayer.cpp ComputeLibrary/utils/Utils.cpp -fPIC -fPIE -I ComputeLibrary/ -I ComputeLibrary/include/ -std=c++11 -L ComputeLibrary/build/  -pie -llog -larm_compute -larm_compute_core -lstdc++ -lm -o testFc_ 

Is this behavior expected ? Or Am I configuring it in wrong way ? Please let me know if you need more details on this.

[FCLayer.txt](https://github.com/ARM-software/ComputeLibrary/files/4546275/FCLayer.txt)

**Comment by morgolock** [comment]
Hi @pateldarsh 

Could you please give us an idea of how much slower is it? The delta should be minimal.

Please also take a look at this: https://github.com/ARM-software/ComputeLibrary/issues/746#issuecomment-534125884

In general, to see a speedup in 8 bit data type vs F32, you have to compiler for arch=armv-8.2a and run the binary on an armv-8.2a CPU. If you do this you could expect an speedup of 1.5x due to the presence of the dot product instructions.

Hope this helps.

**Comment by pateldarsh** [comment]
Hi @morgolock ,

Thank you for reply. 

**8 bit data type processing more than double time taken by FP32**. Which is never expected !! This is on iMX8x board with 4 Cortex A35 cores. It's an android device.

Why armv-8.2a specifically ? My library is compiled with arch=arm64-v8a. Is this not sufficient ?

Could you please tell if there's something wrong in the code I have used ?

Counter to the comment  you have mentioned in [this post](https://github.com/ARM-software/ComputeLibrary/issues/746#issuecomment-534125884), I have observed that Conv2d, Depthwise Conv2d time is reduced by 1.5 / 2 on the same platform, with the same library.

Thanks,
Darshan

**Comment by morgolock** [comment]
Hi @pateldarsh 

What I meant is that in order to see a speedup with the 8 bits data type you need a device with a CPU supporting the dot product instruction. The dot product instruction is supported in arch=arm-v8.2-a.

If your device does not support the dot product instruction the functions running on 8 bits tensors will take more time than FP32. This is expected because there is some additional work in the kernels to convert from 8 bit to 32 bit before computing the results. In the absence of the dot product to compensate, this extra work of conversion is an overhead and that explains the reason why you see the quantized kernels being slower than FP32 counterparts on non armv-8.2a.

Hope this helps.

**Comment by pateldarsh** [comment]
Hi @morgolock ,

Thank you for clarification. But if NEPixelWiseMultiplication takes more time for INT8, Then NEConvolutionLayer timing should also increase ? But I have observed that NEConvolutionLayer layer takes less time for INT8 than FP32.

Does NEConvolutionLayer uses different instruction ? Or it uses the same dot product ?

Has anyone observed timing improvement in NEPixelWiseMultiplication with INT8 ( in any platform ) ? Asking because, Then it leaves only two possiblities, 1) TestApp is wrong 2) Platfrom doesn't support dot product.

Thanks,
Darshan

**Comment by pateldarsh** [comment]
Hi @morgolock ,

I have observed similar behavior on [Renesas RCAR H3 platform](https://www.renesas.com/tw/en/solutions/automotive/soc/r-car-h3.html). It has 4 Cortex A53 and 4 Cortex A57 cores. This is linux based system.

Please help to solve this problem.

Thanks,
Darshan

Thanks,
Darshan

**Comment by morgolock** [comment]
Hi @pateldarsh 

NEPixelWiseMultiplication is not used in NEConvolutionLayer, so I'm a bit confused as to why you mention it. 

What I'm saying is that, in this particular case, NEConvolutionLayer and NEFCLayer on quantized input is expected to be slower than on fp32 due to the absence of the dot instruction.

Obviously there are exceptions and for some particular configurations of shapes this might now hold true. But in general you would expect the behavior described above.

Hope this helps.

**Comment by pateldarsh** [comment]
Hi @morgolock,

Sorry to confuse, I understood that NEConvolutionLayer INT8 processing will take more time compare to FP32 in absence of DOT product instruction. I will check my hardware spec and update.

I have mentioned NEConvolutionLayer, Because it's timing is reduced for INT8 compare to FP32. Does it not use DOT product ? This is observed in multiple experiment.

Please help to understand this inconsistencies.

Thanks,
Darshan

**Comment by morgolock** [comment]
Hi @pateldarsh 

> I understood that NEConvolutionLayer INT8 processing will take more time compare to FP32 in absence of DOT product instruction. I will check my hardware spec and update.

It depends on the CPU you compile for and the size of the workloads. 

NEConvolutionLayer uses the dot product instruction if there is support for it in the CPU you run the workload. If the CPU does not support the dot product, you could expect NEConvolutionLayer for quantized types to be slower than for fp32 (In general for big workloads as you would find in commonly used networks) 

> I have mentioned NEConvolutionLayer, Because it's timing is reduced for INT8 compare to FP32. Does it not use DOT product ? This is observed in multiple experiment.


What are the sizes of your workloads ? What kind of reduction are we speaking about?

**Comment by GeorgeARM** [comment]
Hello @pateldarsh,

As @morgolock mentioned with the presence of dot product you will get much higher performance but this is present in v8.2 architecture. On a regular armv8 there is high probability that your performance might be in par with float. Moreover, there is an issue/bug in the 20.02 release that does not dispatch the optimal kernel sequence for NEFullyConnected layer. This is fixed in oir development repository (https://review.mlplatform.org/#/admin/projects/ml/ComputeLibrary) and will be part of the next release.
Hope it helps.
