### ISSUE TITLE
Should pooling use CEIL?

### ISSUE THREAD

**Issue by joey2014** [ARM-software/ComputeLibrary#82]
For the settings
w 22 h 22 pooled_w 11 pooled_w 11
kernel_size 3 stride_w 2 stride_h 2 pad_w 0 pad_h 0

The default round (FLOOR) cause assert error:
terminate called after throwing an instance of 'std::runtime_error'
  what():  in void arm_compute::NEPoolingLayerKernel::configure(const arm_compute::ITensor*, arm_compute::ITensor*, const arm_compute::PoolingLayerInfo&) src/core/NEON/kernels/NEPoolingLayerKernel.cpp:94: (output->info()->dimension(0) != pooled_w) || (output->info()->dimension(1) != pooled_h)

And when CEIL is used  it can pass verification. In conv we need use FLOOR instead. detail see #66  
Any comment about it? Or can we find any case which should use FLOOR instead?

**Comment by mpflanzer** [comment]
Whether to use `CEIL` or `FLOOR` depends on the respective settings in each use case.
Based on the input size* (`x`), kernel size* (`k`), padding (`p`) and stride (`s`) the expected output size (`o`) is computed as:
```
o = ROUND((x + 2 * p - k) / s) + 1
```
`ROUND` is either `FLOOR` or `CEIL` as specified (or by default `FLOOR` if nothing is specified).

So in your example we have:
```
o = ROUND((22 + 2 * 0 - 3) / 2) + 1
  = ROUND(9.5) + 1
```
Since you want to have a output size* of `11` you need to use `CEIL`. If you'd specified an output size* of `10` `FLOOR` would have worked.

Instead of computing the output size* manually you can use the `arm_compute::scaled_dimensions` function from `arm_compute/core/Utils.h`.

Does this help to explain how the rounding mode affects the output dimensions?

_\* Size can be either width or height._

**Comment by GeorgeARM** [comment]
@mpflanzer 's comment is clear. Closing! Reopen if required!
