### ISSUE TITLE
performance issue for matrix multiplication on a very simple example

### ISSUE THREAD

**Issue by gawain102000** [ARM-software/ComputeLibrary#837]
For the matrix multiplication on  A*B=C, the performance issue was observed as following

First, the processing for initialization and computation is very simple as following
"
CLTensor ATensor;
CLTensor BTensor;
CLTensor OTensor;
......
CLGEMM gemm;
gemm.configure(&BTensor, &ATensor, NULL, &OTensor, 1.0f, 0.0f);
......
gettimeofday(&begin, NULL)
gemm.run()
CLScheduler::get().sync();
gettimeofday(&end,NULL)
......
"

Second, let the total cost for the function "gemm.run()" and "CLScheduler::get().sync()" be COST, the matrix multiplication was measured as following 
1. A= (100000, 512)  B=(512, 1) , COST is about 70ms
2. A= (100000, 512)  B=(512, 2) , COST is about 430ms
3. A= (100000, 512)  B=(512, 3) , COST is about 430ms
4. A= (100000, 512)  B=(512, 4) , COST is about 440ms

There is a big performance gap between 1 and 2,3,4. Why? 

Thanks
Bo

**Comment by gawain102000** [comment]
Hi sicong-li-arm, any update?

Thanks

**Comment by gawain102000** [comment]
Any update?

**Comment by sicong-li-arm** [comment]
Hi @gawain102000  Sorry for the late reply!
There's an important step if you choose to instrument and measure the CLGEMM function manually: you need to run the op multiple times (calling gemm.run() multiple times), and discard the first run. This is because we have a one-off prepare() stage (transform weight tensor, using opencl tuner etc), that is usually invoked the firs time run() is called. This could mess up the performance figures you obtained.

Alternatively, if you just want to see how ComputeLibrary's CLGEMM performs on your platform, you can try using our existing benchmark example framework. To do so, you'll need to build with benchmark_examples=1, debug=0 and asserts=0, then you can use the benchmark_cl_sgemm binary on your platform like so (which runs 10 iterations while discarding the first run):
`./benchmark_cl_sgemm --example_args="100000,1,512" --iterations=10`
However this approach currently only supports single thread.

I tested on a similar platform and didn't find the issue you reported. Could you please give the method above a try and tell us your findings? In this case could you also share with us your build options/command, the hash of the ComputeLibrary you're building, how many threads you're running with, and preferably the full snippets of your code which you use to instrument CLGEMM?

Thanks!

**Comment by gawain102000** [comment]
Hi @sicong-li-arm,
Many thanks for helping!

ComputeLibrary version: 19.08(related libraries were attached in test.zip)
Platform:  Linux + Mali-T860
test code: attached

Compile and run:
1.  unzip test.zip
2.  aarch64-linux-gnu-g++ test.cpp -I. -Iinclude -std=c++11 -L. -larm_compute -larm_compute_core -o test -DARM_COMPUTE_CL 
3.  ./test

From test.cpp, we only run OP once! However, each time before running "gemm.run", we need to change the values of "BTensor",  in order to use other OPs(not first time), how to reach this by code refinement?  (BTW, from our testing, in order to get correct results, each time before running "gemm.run", need to run "gemm.configure" too. right? ) 
[test.zip](https://github.com/ARM-software/ComputeLibrary/files/4953071/test.zip)

Thanks!

**Comment by sicong-li-arm** [comment]
Hi @gawain102000 ! 

You don't need to re-configure the gemm op if only the values of a tensor change. Therefore you can configure gemm once before entering the loop, then call gemm.run immediately after configure, but before entering the loop, this would be a dummy run which would include the prepare stage. Then within the loop you can permute the tensor values, and measure the execution time of gemm.run(). To get a more reliable measurement, you can collect the execution time of gemm.run() within the loop, then in the end get the average/minimum value, which would be a quite decent estimate of how fast gemm runs.

I've made the necessary changes to your source code and added some more comments. Please see the attached file:
[test_commented.zip](https://github.com/ARM-software/ComputeLibrary/files/4994862/test_commented.zip)

Kind regards!

**Comment by gawain102000** [comment]
Hi @sicong-li-arm,
Many thanks for commenting and suggesting! 

Following your commenting, we will test it later on some devices. Once getting the results, will update

Thanks

**Comment by gawain102000** [comment]
Many thanks @sicong-li-arm！ 

By testing on 3 devices, the result look good now as following,

    A=(1, 512) B= (512, 100000), COST is about 111ms
    A=(2, 512) B= (512, 100000), COST is about 145ms
    A=(3, 512) B= (512, 100000), COST is about 178ms
    A=(4, 512) B= (512, 100000), COST is about  221ms

Since the result looks expected, let me close this issue. 
Thanks again!
