### ISSUE TITLE
Turning off NEON

### ISSUE THREAD

**Issue by taehyunzzz** [ARM-software/ComputeLibrary#841]
I am trying to compare the execution time (or execution cycles) of executing ./graph_alexnet when NEON is turned on/off.
I can run the code for NEON=1, but how do I run the code with NEON=0?
Will building with neon=0 be the solution?

Thanks

**Comment by sanpar02** [comment]
Hi @taehyunzzz 

If you want to completely exclude the NEON from the build, NEON=0 would be the answer. As a result, the build won't have any NEON kernels, which means the build should use other means (e.g., OpenCL) for all the computation.

However, if you want to compare performance between execution on the same CPU "with NEON instructions" and "without NEON instructions", I don't think we currently support that scenario. Since optimization on each kernel consists of various aspects, kernels are not capable of excluding NEON instruction from their optimized computation.

Hope it helps.

Thanks.

**Comment by sanpar02** [comment]
I believe this has been answered, so I'm closing this issue.
Please reopen or create a new issue if there is anything we can help.
