### ISSUE TITLE
Kirin 960   opencl run slower than cpu

### ISSUE THREAD

**Issue by mathpopo** [ARM-software/ComputeLibrary#848]
https://github.com/ARM-software/ComputeLibrary/issues/846
cpu is Kirin 960

**Comment by mathpopo** [comment]
@sanpar02   yes ,maybe i just use mtk gpu,so many error, i look for a real G71
 but seems opencl not faster

![234](https://user-images.githubusercontent.com/21274466/88239872-2977fe80-ccb8-11ea-9ff5-6c0760c6ce30.jpeg)





![123](https://user-images.githubusercontent.com/21274466/88239308-9f7b6600-ccb6-11ea-9476-23df21202ca6.jpeg)


_mnist --example_args=--target=NEON --iteration=1000 <
Version = arm_compute_version=v20.05 Build options: {'arch': 'arm64-v8a', 'neon': '1', 'opencl': '1', 'embed_kernels': '1', 'extra_cxx_flags': '-fPIC', 'benchmark_tests': '0', 'validation_tests': '0', 'os': 'android'} Git hash=b'6a7771e460abeac7d401d6d38a0fcf0a0d2c3cbe'
CommandLine = ./benchmark_graph_mnist --example_args=--target=NEON --iteration=1000
CL_DEVICE_VERSION = OpenCL 2.0 v1.r14p0-00cet0.9500166da1423e9591394b068a52b758
Iterations = 1
Running [0] 'Examples/benchmark_graph_mnist'
Threads : 1
Target : NEON
Data type : F32
Data layout : NHWC
Tuner enabled? : false
Cache enabled? : false
Tuner mode : Normal
Tuner file :
Fast math enabled? : false

Wall clock/Wall clock time: AVG=2084.0000 us
Executed 1 test(s) (1 passed, 0 expected failures, 0 failed, 0 crashed, 0 disabled) in 0 second(s)
aph_mnist --example_args=--target=CL --iteration=1000 <
Version = arm_compute_version=v20.05 Build options: {'arch': 'arm64-v8a', 'neon': '1', 'opencl': '1', 'embed_kernels': '1', 'extra_cxx_flags': '-fPIC', 'benchmark_tests': '0', 'validation_tests': '0', 'os': 'android'} Git hash=b'6a7771e460abeac7d401d6d38a0fcf0a0d2c3cbe'
CommandLine = ./benchmark_graph_mnist --example_args=--target=CL --iteration=1000
CL_DEVICE_VERSION = OpenCL 2.0 v1.r14p0-00cet0.9500166da1423e9591394b068a52b758
Iterations = 1
Running [0] 'Examples/benchmark_graph_mnist'
Threads : 1
Target : CL
Data type : F32
Data layout : NHWC
Tuner enabled? : false
Cache enabled? : true
Tuner mode : Normal
Tuner file :
Fast math enabled? : false

Wall clock/Wall clock time: AVG=2773.0000 us
Executed 1 test(s) (1 passed, 0 expected failures, 0 failed, 0 crashed, 0 disabled) in 2 second(s)

**Comment by sanpar02** [comment]
Hi @mathpopo 

As far as I understand, Kirin960 is SoC with Cortex-A73/A53 cluster with Mali-G71, could you confirm it?

As I said in the previous issue, there is a good chance for the CPU to outperform the GPU since the network is relatively small one. We'll investigate if we are getting similar results and update this ticket.

Thanks.

**Comment by mathpopo** [comment]
@sanpar02  i just see phone info ,  could you offer me some command to help me to confirm it?

if because the net so small to lead to this , i will change to use a big (yolo) to test it

**Comment by sanpar02** [comment]
Hi @mathpopo 

With most of Linux, you can find information about your CPU by `cat /proc/cpuinfo`. However, the way I deduced the CPU model is the "CPU Architecture" field in your screenshot. The value is 0xd09 and it is part number of Cortex-A73, so I wanted to double-check.
I haven't tried this myself yet, but if you could other big networks at your end, it would be very nice.

Thanks.

**Comment by mathpopo** [comment]
@sanpar02  i guess:
step1 put data into tensor from cpu->gpu
step2 run session
step3 get output from gpu->cpu

if cup mode:
no need step 1,3

if gpu mode:
need 3 step3

if cost time happen in cpu ,total time is step 2

if gpu :step(1+2+3)

but we know : copy data from cpu->gpu or gpu->cpu is too much 

so i doubt the CL cost more time is this 

so i will log system time in c++ file to test it

**Comment by sanpar02** [comment]
Hi @mathpopo 

I've done the experiment myself using a board with Kirin960 and got similar results (CPU is faster).
Also, I think your analysis is valid and it backs up one of our previous discussions - the network is too small to utilize GPU's capability.
Unfortunately, as far as I understand, we currently don't have dedicated APIs for profiling. You still can try to use standard C++ functions, but it might lead you incorrect analysis since it will affect the execution time (which in this case is quite short).

Hope it helped.

Thanks.
