### ISSUE TITLE
INT8 addition taking longer execution time than FP32

### ISSUE THREAD

**Issue by pranathibl** [ARM-software/ComputeLibrary#875]
Hi,

I am trying to use addition layer with INT8 inputs. Execution time for INT8 addition is much longer than FP32 addition.

ACL Version: v20.02.1

[additionLayer_standalone_Int8.zip](https://github.com/ARM-software/ComputeLibrary/files/5987218/additionLayer_standalone_Int8.zip)

Thanks
Pranathi

**Comment by morgolock** [comment]
Hi @pranathibl 

Could you please let us know which platform have you run this test?

Could you please try with the latest release of ACL  v20.11?

Hope this helps.

**Comment by pranathibl** [comment]
Hi @morgolock 

I am using Raspberry Pi 3, Model-B quad core ARM Cortex @1.2GHz with 1GB RAM.

I have tried using v20.11. I see there is performance improvement with v20.11 from v20.02.1 for INT8 inputs. but it is still much more than FP32 implementation. Is it expected for FP32 to perform better?

-Pranathi

**Comment by morgolock** [comment]
Hi @pranathibl 

Yes, this is expected due to the required additional instructions to convert from int8 to float and back, you can see it here https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/NEON/kernels/NEArithmeticAdditionKernel.cpp#L475

In the FP32 kernel there is no conversion required, just load, add and store: https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/NEON/kernels/NEArithmeticAdditionKernel.cpp#L124
