### ISSUE TITLE
What does the build flag tracing=1 do?

### ISSUE THREAD

**Issue by agarwal-ayushi** [ARM-software/ComputeLibrary#888]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
ARM CL v19.05

**Platform:**

**Operating System:**
Linux

**Problem description:**
I need some help to understand how to use the flag `tracing=1` while running an application.

**Comment by morgolock** [comment]
Hi @agarwal-ayushi 

This was an experimental feature for debugging and dumping runtime's function configurations.

In order to use this function you have to build with tracing=1 and use https://github.com/ARM-software/ComputeLibrary/blob/master/scripts/enable_tracing.py

This script makes changes to ACL's source code, for every function in the runtime adds some additional code to dump the configuration values.

The tracing feature is not longer maintained.
