### ISSUE TITLE
ACL on Cortex-R52

### ISSUE THREAD

**Issue by uu-praveeng** [ARM-software/ComputeLibrary#897]
Hi,
Can I compile ACL examples on Cortex-R52 arm architectures. Since Cortex-R52 and Cortex-R82 already supports Neon extensions as per the attached doc.
[Arm Cortex-R Comparison Table (7).pdf](https://github.com/ARM-software/ComputeLibrary/files/6391104/Arm.Cortex-R.Comparison.Table.7.pdf)

Thanks,
Praveen.

**Comment by sanpar02** [comment]
Hi,

Thanks for your question.

Unfortunately, Compute Library doesn't support Cortex-R52 at the moment.

As mentioned in the previous release note (https://github.com/ARM-software/ComputeLibrary/blob/7dcb9fadb98cad05fca72de3273311d570d98b4e/docs/00_introduction.dox#L94), the library supports only Armv8-R **AArch64** architecture (Cortex-R82 is based on this architecture), whereas Cortex-R52 is Armv8-R.

Hope it helps and please re-open if you need any further information.

**Comment by uu-praveeng** [comment]
I might be asking some naive questions here. Please bear with me . 
Isn't  Neon extension support enough for bringing in ACL to Cortex-R52 which has amrv8-r + Neon extension based processor?
On a similar note armv7-a + Neon which is based on 32bit architecture still supports ACL. Is this a good comparison to analyze the problem.

Is there any other factor that is blocking ACL to be run on Cortex-R52. Could you point me to any documentation that I can refer to understand why ACL cannot be used in Cortex-R52.

Reason for me iterating on this. We have customer use cases who are looking for deployment of CNNs to Corrtex-R52. If we could leverage on ACL it will be a huge boost for us.

**Comment by sanpar02** [comment]
I think the biggest difference between Armv8-R (without AArch64) and Armv7-A (32-bit) is existence of MMU. Since Compute Library's main target is feature-rich OSes such as Linux, MMU is currently essential. (We support bare-metal platforms, but those have been tested only with the same architecture that can run those OSes)

As you corrected pointed out, 64-bit registers are not essential. So, theoretically, we could try to "port" the library to Armv8-R architecture for bare-metal platforms or OSes that don't use MMU. However, we currently don't have plan for those activities as far as I'm aware.

Hope it helps.
