### ISSUE TITLE
Does ComputeLibrary support be built on windows system

### ISSUE THREAD

**Issue by laoniangjiu** [ARM-software/ComputeLibrary#900]
Hi, I saw the supported system of ComputeLibrary was not include windows system. Is it possible to build ComputeLibrary with cmake and virtual studio 2019 on windows system. If not, whether there are plans to support it, since the arm-based PC will release soon.

**Comment by morgolock** [comment]
Hi @laoniangjiu 

It is possible to build on windows but I would suggest using Linux or MacOS because all the tools used to build the library are unix tools.

Please take a look at the documentation: https://arm-software.github.io/ComputeLibrary/v21.05/how_to_build.xhtml#S1_6_windows_host

Hope this helps.
