### ISSUE TITLE
How to run the example in a bare metal environment？

### ISSUE THREAD

**Issue by Derekduke** [ARM-software/ComputeLibrary#910]
My goal is to use ACL to complete target detection on bare metal：
Platform：imx6ull (arm cortex-a7)
OS: bare metal or RTOS

I have successfully compiled ACL on the linux platform by:
**_scons arch=armv7a os=bare_metal build_dir=bm -j52 Werror=1 opencl=0 neon=1 debug=0 asserts=1 standalone=1 validation_tests=1 examples=1 openmp=0 cppthreads=0_**

Now i got the following file：
**_libarm_compute_core-static.a libarm_compute_graph-static.a libarm_compute-static.a src_**

It is expected to be used as a software package of RTOS, but now I don’t know how to run the example. It seems that the official tutorial only mentions how to compile the ACL library used by bare metal, and does not give an example of how to apply it. For example, for alexnet, how do I import the model file and run the main function program in a bare metal environment?

**Comment by mpekatsoula** [comment]
Hi @Derekduke 

Using the latest ACL version when you build with examples=1 you'll get the graph examples generated in the build folder. Then you have  to provide the weights using the --data option.

More info about the examples' arguments here: https://arm-software.github.io/ComputeLibrary/v21.05/how_to_build.xhtml#S1_2_2_examples

**Comment by Derekduke** [comment]
> Hi @Derekduke
> 
> Using the latest ACL version when you build with examples=1 you'll get the graph examples generated in the build folder. Then you have to provide the weights using the --data option.
> 
> More info about the examples' arguments here: https://arm-software.github.io/ComputeLibrary/v21.05/how_to_build.xhtml#S1_2_2_examples

**Comment by Derekduke** [comment]
Hi @mpekatsoula 

I reset git clone to the latest version of ACL, and make sure that example = 1 is turned on. However, only one folder “bm” is generated in the build folder without "example".

**Comment by mpekatsoula** [comment]
Hi @Derekduke,

Just noticed that you are building for armv7a. We currently don't automatically generate the examples/tests with armv7a + bare_metal (a warning is printed when you try to build). I'll put this into our backlog in order to fix it.

Until then, once you build the library you can manually compile an example like this:
`arm-eabi-g++ -o build/bm/examples/graph_vgg16 -fstack-protector-strong -static-libgcc -static-libstdc++ -static -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -Wl,--whole-archive build/bm/libarm_compute_graph-static.a -Wl,--no-whole-archive build/bm/examples/graph_vgg16.o build/bm/utils/Utils.o build/bm/utils/GraphUtils.o build/bm/utils/CommonGraphOptions.o -Lbuild/bm -L. build/bm/libarm_compute-static.a build/bm/libarm_compute_core-static.a`

and then run your example under ./build/bm/examples/graph_vgg16.
