### ISSUE TITLE
ARM Assembly vs. C - Performance?

### ISSUE THREAD

**Issue by einthusan** [ARM-software/ComputeLibrary#931]
I am seeing several SIMD libraries for ARM on Github, and am not sure which to choose from. Is there any performance benchmarks for this library? I also noticed that C intrinsics are being used, whereas ARM assembly has been shown to be more performant, or am I wrong here?

In short, why is ARM assembly not used and are there performance benchmarks comparing other similar libraries?

Thanks in advance!

**Comment by morgolock** [comment]
Hi @einthusan 

ACL has kernels written in assembly to optimize critical workloads like GEMM for various ARM CPUs. You can see the sources here: https://github.com/ARM-software/ComputeLibrary/tree/master/src/core/NEON/kernels/arm_gemm/kernels

For some workloads like GEMM you get a considerable speedup when using assembly but this is not the same for all operators and that's why we implement some of them in C++ and intrinsics.

To have a better idea of ACL performance, please take a look at performance section in this page:
https://developer.arm.com/ip-products/processors/machine-learning/compute-library

Hope this helps.
