### ISSUE TITLE
Build ACL22_05 failed with aarch64-linux-android-ar: Permission denied

### ISSUE THREAD

**Issue by Chernobyl81** [ARM-software/ComputeLibrary#984]
Hi, when I build library with NDK r23b use  command `scons arch=arm64-v8a neon=1 opencl=1 embed_kernels=1 extra_cxx_flags="-fPIC"  benchmark_tests=0 validation_tests=0 os=android -j16`  occurs errors:

`sh: 1: aarch64-linux-android-ar: Permission denied`
 
![企业微信截图_16566594203718](https://user-images.githubusercontent.com/1080172/176843297-04a89471-6217-4d82-b7aa-ea28168c5aca.png)

**Comment by morgolock** [comment]
Hi @Chernobyl81 

There is a permissions problem with your host environment or toollchain. 

In your build command: `scons arch=arm64-v8a neon=1 opencl=1 embed_kernels=1 extra_cxx_flags="-fPIC" benchmark_tests=0 validation_tests=0 os=android -j16`  you don't specify the path to the toolchain so I'm not sure how and where scons finds  `aarch64-linux-android-ar` and `aarch64-linux-android-clang++`.

Did you add the toolchain path to the `$PATH` variable? If so what happens if you manually try to run `aarch64-linux-android-ar` ?

**Comment by morgolock** [comment]
Hi @Chernobyl81 

Please try to specify the archiver tool as show below with the `AR=llvm-ar` variable:

`AR=llvm-ar CXX=clang++ CC=clang PATH=../../toolchains/android-ndk-r24/toolchains/llvm/prebuilt/linux-x86_64/bin/:$PATH scons neon=1 opencl=0   benchmark_tests=0 validation_tests=1 benchmark_examples=1 standalone=0 os=android Werror=0 test_filter=ActivationLayer.cpp compiler_prefix=aarch64-linux-android31- toolchain_prefix=llvm- arch=arm64-v8.2-a-sve -j8`

Hope this helps.

**Comment by Chernobyl81** [comment]
Hi, @morgolock When I set neon=0, it works fine.  Building occurs errors when I set neon=1 
![企业微信截图_16568994782244](https://user-images.githubusercontent.com/1080172/177068322-78d4a19d-676a-494e-b4a1-783da43bfe38.png)

**Comment by morgolock** [comment]
Hi @Chernobyl81 

Please try with `arch=armv8a` instead of `arch=arm64-v8.2-a-sve`

Hope this helps

**Comment by Chernobyl81** [comment]
Wow, it works, thanks a lot! @morgolock
