### ISSUE TITLE
Compile arm64 code from x86 OSX as a host

### ISSUE THREAD

**Issue by ilya-lavrenov** [ARM-software/ComputeLibrary#994]
**Output of 'strings libarm_compute.so | grep arm_compute_version':** https://github.com/ARM-software/ComputeLibrary/tree/v22.08

**Platform:** Apple with x86 processor 

**Operating System:** OSX 12

**Problem description:**

We are trying to build arm64 binaries on Apple x86 host, see https://github.com/openvinotoolkit/openvino_contrib/pull/416
The cmake is able to handle such scenario correctly and provides different variables, like:
```
            -DCMAKE_SYSTEM_NAME=Darwin
            -DCMAKE_SYSTEM_PROCESSOR=arm64
            -DCMAKE_OSX_ARCHITECTURES=arm64
```
And it allows to compile generic code for arm64, but for ARM Compute library we have:
```
error: unknown target CPU 'armv8.6-a' 
note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, icelake-server, tigerlake, sapphirerapids, alderlake, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, znver3, x86-64, x86-64-v2, x86-64-v3, x86-64-v4 
```
Can we fix this?

**Comment by morgolock** [comment]
Hi @ilya-lavrenov 

The version of `clang++` that you are using does not support `arch=armv8.6-a` , this looks like a problem in the toolchain rather than in Arm Compute Library.

```
2022-09-04T21:38:14.1657400Z cd /Users/runner/work/1/openvino_contrib/modules/arm_plugin/thirdparty/ComputeLibrary && /usr/local/Cellar/cmake/3.24.1/bin/cmake -E env /usr/local/bin/scons neon=1 opencl=0 cppthreads=1 embed_kernels=0 examples=0 Werror=0 data_layout_support=nchw build_dir=/Users/runner/work/1/_w/build/build-modules/arm_plugin/thirdparty arch=armv8.6-a os=macos compiler_cache=ccache extra_cxx_flags=-fPIC\ \ -fsigned-char\ -ffunction-sections\ -fdata-sections\ -fdiagnostics-show-option\ -Wundef\ -Wreturn-type\ -Wunused-variable\ -Wswitch\ -Wno-error=deprecated-declarations\ -Wno-undef\ -Wno-error=return-stack-address
2022-09-04T21:38:14.1759910Z scons: Reading SConscript files ...
2022-09-04T21:38:14.1861310Z Using compilers:
2022-09-04T21:38:14.1936420Z CC ccache clang
2022-09-04T21:38:14.2037460Z CXX ccache clang++
```

In the command above `scons` is not pointing to a cross-compiler and instead is trying to use the native host compiler which does not support arm64 targets. The CPU targets listed in the error message are not ARM targets:

```
2022-09-04T21:38:14.8329760Z note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, icelake-server, tigerlake, sapphirerapids, alderlake, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, znver3, x86-64, x86-64-v2, x86-64-v3, x86-64-v4
```

To fix this you should update the PATH variable when you call scons to point to the correct `clang++` version which supports arm64.

Something like this:
```PATH=$PATH:../../toolchains/android-ndk-r23-beta5/toolchains/llvm/prebuilt/linux-x86_64/bin/ scons arch=armv8.6-a-sve neon=1 opencl=0 embed_kernels=1 extra_cxx_flags="-fPIC" benchmark_tests=0 validation_tests=0 ....```


Hope this helps.

**Comment by ilya-lavrenov** [comment]
@morgolock why the same version of compiler works for code which is build using cmake, and does not work when we build ARM compute via scons? :) didn't you find it strange?
The compiler on OSX 11 and higher supports both arm64 and x86_64 instructions via -arch option. This is mapped on CMAKE_OSX_ARCHITECTURES:
- if it contains -DCMAKE_OSX_ARCHITECTURES=x86_64, -arch x86_64 is added and binary x86 is compiled
- if it contains -DCMAKE_OSX_ARCHITECTURES=arm64, -arch arm64 is added and binary arm64 is compiled
- if it contains both -DCMAKE_OSX_ARCHITECTURES=arm64;x86_64, then universal binary is compiled which contains both instructions.
So, we expect that ARM compute build system can reuse this capability and allow to compile with universal clang arm64 on x86 architecture (read https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary). In general, default clang is already able to cross-compile

Thanks,
Ilya.

**Comment by morgolock** [comment]
Hi @ilya-lavrenov 

Yes, I'll look into the scons files because we have not tested cross-compilation on macos.

> The compiler on OSX 11 and higher supports both arm64 and x86_64 instructions via -arch option. This is mapped on CMAKE_OSX_ARCHITECTURES:
>  if it contains -DCMAKE_OSX_ARCHITECTURES=x86_64, -arch x86_64 is added and binary x86 is compiled
    if it contains -DCMAKE_OSX_ARCHITECTURES=arm64, -arch arm64 is added and binary arm64 is compiled
    if it contains both -DCMAKE_OSX_ARCHITECTURES=arm64;x86_64, then universal binary is compiled which contains both instructions.

I however don't see how this could possibly work because these `cmake` variables won't affect `scons` at all. 

To cross-compile ACL you will need to change the build command to point it to a toolchain that supports arm64 targets, simply add the path variable to this command and make it point to the correct toolchain:

 ` cd /Users/runner/work/1/openvino_contrib/modules/arm_plugin/thirdparty/ComputeLibrary && /usr/local/Cellar/cmake/3.24.1/bin/cmake -E env /usr/local/bin/scons neon=1 opencl=0 cppthreads=1 embed_kernels=0 examples=0 Werror=0 data_layout_support=nchw build_dir=/Users/runner/work/1/_w/build/build-modules/arm_plugin/thirdparty arch=armv8.6-a os=macos compiler_cache=ccache extra_cxx_flags=-fPIC\ \ -fsigned-char\ -ffunction-sections\ -fdata-sections\ -fdiagnostics-show-option\ -Wundef\ -Wreturn-type\ -Wunused-variable\ -Wswitch\ -Wno-error=deprecated-declarations\ -Wno-undef\ -Wno-error=return-stack-address`

Would this potential solution work for you?

Hope this helps.

**Comment by ilya-lavrenov** [comment]
Done WA via cross-compilation https://github.com/openvinotoolkit/openvino_contrib/pull/438
